/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private TColchetesEsquerda _colchetesEsquerda_;
    private final LinkedList<PDeclaracoesBloco> _declaracoesBloco_ = new LinkedList<PDeclaracoesBloco>();
    private final LinkedList<PComandosBloco> _comandosBloco_ = new LinkedList<PComandosBloco>();
    private TColchetesDireita _colchetesDireita_;
    private PElseOpcional _elseOpcional_;

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") TColchetesEsquerda _colchetesEsquerda_,
        @SuppressWarnings("hiding") List<?> _declaracoesBloco_,
        @SuppressWarnings("hiding") List<?> _comandosBloco_,
        @SuppressWarnings("hiding") TColchetesDireita _colchetesDireita_,
        @SuppressWarnings("hiding") PElseOpcional _elseOpcional_)
    {
        // Constructor
        setColchetesEsquerda(_colchetesEsquerda_);

        setDeclaracoesBloco(_declaracoesBloco_);

        setComandosBloco(_comandosBloco_);

        setColchetesDireita(_colchetesDireita_);

        setElseOpcional(_elseOpcional_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneNode(this._colchetesEsquerda_),
            cloneList(this._declaracoesBloco_),
            cloneList(this._comandosBloco_),
            cloneNode(this._colchetesDireita_),
            cloneNode(this._elseOpcional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public TColchetesEsquerda getColchetesEsquerda()
    {
        return this._colchetesEsquerda_;
    }

    public void setColchetesEsquerda(TColchetesEsquerda node)
    {
        if(this._colchetesEsquerda_ != null)
        {
            this._colchetesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colchetesEsquerda_ = node;
    }

    public LinkedList<PDeclaracoesBloco> getDeclaracoesBloco()
    {
        return this._declaracoesBloco_;
    }

    public void setDeclaracoesBloco(List<?> list)
    {
        for(PDeclaracoesBloco e : this._declaracoesBloco_)
        {
            e.parent(null);
        }
        this._declaracoesBloco_.clear();

        for(Object obj_e : list)
        {
            PDeclaracoesBloco e = (PDeclaracoesBloco) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaracoesBloco_.add(e);
        }
    }

    public LinkedList<PComandosBloco> getComandosBloco()
    {
        return this._comandosBloco_;
    }

    public void setComandosBloco(List<?> list)
    {
        for(PComandosBloco e : this._comandosBloco_)
        {
            e.parent(null);
        }
        this._comandosBloco_.clear();

        for(Object obj_e : list)
        {
            PComandosBloco e = (PComandosBloco) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandosBloco_.add(e);
        }
    }

    public TColchetesDireita getColchetesDireita()
    {
        return this._colchetesDireita_;
    }

    public void setColchetesDireita(TColchetesDireita node)
    {
        if(this._colchetesDireita_ != null)
        {
            this._colchetesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colchetesDireita_ = node;
    }

    public PElseOpcional getElseOpcional()
    {
        return this._elseOpcional_;
    }

    public void setElseOpcional(PElseOpcional node)
    {
        if(this._elseOpcional_ != null)
        {
            this._elseOpcional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseOpcional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colchetesEsquerda_)
            + toString(this._declaracoesBloco_)
            + toString(this._comandosBloco_)
            + toString(this._colchetesDireita_)
            + toString(this._elseOpcional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colchetesEsquerda_ == child)
        {
            this._colchetesEsquerda_ = null;
            return;
        }

        if(this._declaracoesBloco_.remove(child))
        {
            return;
        }

        if(this._comandosBloco_.remove(child))
        {
            return;
        }

        if(this._colchetesDireita_ == child)
        {
            this._colchetesDireita_ = null;
            return;
        }

        if(this._elseOpcional_ == child)
        {
            this._elseOpcional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colchetesEsquerda_ == oldChild)
        {
            setColchetesEsquerda((TColchetesEsquerda) newChild);
            return;
        }

        for(ListIterator<PDeclaracoesBloco> i = this._declaracoesBloco_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaracoesBloco) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PComandosBloco> i = this._comandosBloco_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandosBloco) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._colchetesDireita_ == oldChild)
        {
            setColchetesDireita((TColchetesDireita) newChild);
            return;
        }

        if(this._elseOpcional_ == oldChild)
        {
            setElseOpcional((PElseOpcional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
