/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AComando extends PComando
{
    private PComandoComposto _comandoComposto_;

    public AComando()
    {
        // Constructor
    }

    public AComando(
        @SuppressWarnings("hiding") PComandoComposto _comandoComposto_)
    {
        // Constructor
        setComandoComposto(_comandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new AComando(
            cloneNode(this._comandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComando(this);
    }

    public PComandoComposto getComandoComposto()
    {
        return this._comandoComposto_;
    }

    public void setComandoComposto(PComandoComposto node)
    {
        if(this._comandoComposto_ != null)
        {
            this._comandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoComposto_ == child)
        {
            this._comandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoComposto_ == oldChild)
        {
            setComandoComposto((PComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
