/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AConstanteDeclaracaoInicial extends PDeclaracaoInicial
{
    private TUnalterable _unalterable_;
    private PTipo _tipo_;
    private TId _id_;
    private PInicializacaoConstante _inicializacaoConstante_;
    private TPontoVirgula _pontoVirgula_;

    public AConstanteDeclaracaoInicial()
    {
        // Constructor
    }

    public AConstanteDeclaracaoInicial(
        @SuppressWarnings("hiding") TUnalterable _unalterable_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PInicializacaoConstante _inicializacaoConstante_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setUnalterable(_unalterable_);

        setTipo(_tipo_);

        setId(_id_);

        setInicializacaoConstante(_inicializacaoConstante_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AConstanteDeclaracaoInicial(
            cloneNode(this._unalterable_),
            cloneNode(this._tipo_),
            cloneNode(this._id_),
            cloneNode(this._inicializacaoConstante_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstanteDeclaracaoInicial(this);
    }

    public TUnalterable getUnalterable()
    {
        return this._unalterable_;
    }

    public void setUnalterable(TUnalterable node)
    {
        if(this._unalterable_ != null)
        {
            this._unalterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unalterable_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PInicializacaoConstante getInicializacaoConstante()
    {
        return this._inicializacaoConstante_;
    }

    public void setInicializacaoConstante(PInicializacaoConstante node)
    {
        if(this._inicializacaoConstante_ != null)
        {
            this._inicializacaoConstante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializacaoConstante_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unalterable_)
            + toString(this._tipo_)
            + toString(this._id_)
            + toString(this._inicializacaoConstante_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unalterable_ == child)
        {
            this._unalterable_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._inicializacaoConstante_ == child)
        {
            this._inicializacaoConstante_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unalterable_ == oldChild)
        {
            setUnalterable((TUnalterable) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._inicializacaoConstante_ == oldChild)
        {
            setInicializacaoConstante((PInicializacaoConstante) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
