/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalSimplesComandoComposto extends PComandoComposto
{
    private TJust _just_;
    private TIn _in_;
    private TCase _case_;
    private TThat2 _that2_;
    private TParentesesEsquerda _parentesesEsquerda_;
    private PExp _exp_;
    private TParentesesDireita _parentesesDireita_;
    private TDo _do_;
    private PComandoComposto _comandoComposto_;

    public ACondicionalSimplesComandoComposto()
    {
        // Constructor
    }

    public ACondicionalSimplesComandoComposto(
        @SuppressWarnings("hiding") TJust _just_,
        @SuppressWarnings("hiding") TIn _in_,
        @SuppressWarnings("hiding") TCase _case_,
        @SuppressWarnings("hiding") TThat2 _that2_,
        @SuppressWarnings("hiding") TParentesesEsquerda _parentesesEsquerda_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParentesesDireita _parentesesDireita_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PComandoComposto _comandoComposto_)
    {
        // Constructor
        setJust(_just_);

        setIn(_in_);

        setCase(_case_);

        setThat2(_that2_);

        setParentesesEsquerda(_parentesesEsquerda_);

        setExp(_exp_);

        setParentesesDireita(_parentesesDireita_);

        setDo(_do_);

        setComandoComposto(_comandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalSimplesComandoComposto(
            cloneNode(this._just_),
            cloneNode(this._in_),
            cloneNode(this._case_),
            cloneNode(this._that2_),
            cloneNode(this._parentesesEsquerda_),
            cloneNode(this._exp_),
            cloneNode(this._parentesesDireita_),
            cloneNode(this._do_),
            cloneNode(this._comandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalSimplesComandoComposto(this);
    }

    public TJust getJust()
    {
        return this._just_;
    }

    public void setJust(TJust node)
    {
        if(this._just_ != null)
        {
            this._just_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._just_ = node;
    }

    public TIn getIn()
    {
        return this._in_;
    }

    public void setIn(TIn node)
    {
        if(this._in_ != null)
        {
            this._in_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._in_ = node;
    }

    public TCase getCase()
    {
        return this._case_;
    }

    public void setCase(TCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    public TThat2 getThat2()
    {
        return this._that2_;
    }

    public void setThat2(TThat2 node)
    {
        if(this._that2_ != null)
        {
            this._that2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._that2_ = node;
    }

    public TParentesesEsquerda getParentesesEsquerda()
    {
        return this._parentesesEsquerda_;
    }

    public void setParentesesEsquerda(TParentesesEsquerda node)
    {
        if(this._parentesesEsquerda_ != null)
        {
            this._parentesesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerda_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParentesesDireita getParentesesDireita()
    {
        return this._parentesesDireita_;
    }

    public void setParentesesDireita(TParentesesDireita node)
    {
        if(this._parentesesDireita_ != null)
        {
            this._parentesesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireita_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PComandoComposto getComandoComposto()
    {
        return this._comandoComposto_;
    }

    public void setComandoComposto(PComandoComposto node)
    {
        if(this._comandoComposto_ != null)
        {
            this._comandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._just_)
            + toString(this._in_)
            + toString(this._case_)
            + toString(this._that2_)
            + toString(this._parentesesEsquerda_)
            + toString(this._exp_)
            + toString(this._parentesesDireita_)
            + toString(this._do_)
            + toString(this._comandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._just_ == child)
        {
            this._just_ = null;
            return;
        }

        if(this._in_ == child)
        {
            this._in_ = null;
            return;
        }

        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        if(this._that2_ == child)
        {
            this._that2_ = null;
            return;
        }

        if(this._parentesesEsquerda_ == child)
        {
            this._parentesesEsquerda_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parentesesDireita_ == child)
        {
            this._parentesesDireita_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._comandoComposto_ == child)
        {
            this._comandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._just_ == oldChild)
        {
            setJust((TJust) newChild);
            return;
        }

        if(this._in_ == oldChild)
        {
            setIn((TIn) newChild);
            return;
        }

        if(this._case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        if(this._that2_ == oldChild)
        {
            setThat2((TThat2) newChild);
            return;
        }

        if(this._parentesesEsquerda_ == oldChild)
        {
            setParentesesEsquerda((TParentesesEsquerda) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parentesesDireita_ == oldChild)
        {
            setParentesesDireita((TParentesesDireita) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._comandoComposto_ == oldChild)
        {
            setComandoComposto((PComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
