/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesBloco extends PDeclaracoesBloco
{
    private PDeclaracaoBloco _declaracaoBloco_;

    public ADeclaracoesBloco()
    {
        // Constructor
    }

    public ADeclaracoesBloco(
        @SuppressWarnings("hiding") PDeclaracaoBloco _declaracaoBloco_)
    {
        // Constructor
        setDeclaracaoBloco(_declaracaoBloco_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesBloco(
            cloneNode(this._declaracaoBloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesBloco(this);
    }

    public PDeclaracaoBloco getDeclaracaoBloco()
    {
        return this._declaracaoBloco_;
    }

    public void setDeclaracaoBloco(PDeclaracaoBloco node)
    {
        if(this._declaracaoBloco_ != null)
        {
            this._declaracaoBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoBloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoBloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoBloco_ == child)
        {
            this._declaracaoBloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoBloco_ == oldChild)
        {
            setDeclaracaoBloco((PDeclaracaoBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
