/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoes extends PDeclaracoes
{
    private TIt _it_;
    private TPresents _presents_;
    private TDoisPontos _doisPontos_;
    private final LinkedList<PDeclaracaoInicial> _declaracaoInicial_ = new LinkedList<PDeclaracaoInicial>();

    public ADeclaracoes()
    {
        // Constructor
    }

    public ADeclaracoes(
        @SuppressWarnings("hiding") TIt _it_,
        @SuppressWarnings("hiding") TPresents _presents_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_,
        @SuppressWarnings("hiding") List<?> _declaracaoInicial_)
    {
        // Constructor
        setIt(_it_);

        setPresents(_presents_);

        setDoisPontos(_doisPontos_);

        setDeclaracaoInicial(_declaracaoInicial_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoes(
            cloneNode(this._it_),
            cloneNode(this._presents_),
            cloneNode(this._doisPontos_),
            cloneList(this._declaracaoInicial_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoes(this);
    }

    public TIt getIt()
    {
        return this._it_;
    }

    public void setIt(TIt node)
    {
        if(this._it_ != null)
        {
            this._it_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._it_ = node;
    }

    public TPresents getPresents()
    {
        return this._presents_;
    }

    public void setPresents(TPresents node)
    {
        if(this._presents_ != null)
        {
            this._presents_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._presents_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    public LinkedList<PDeclaracaoInicial> getDeclaracaoInicial()
    {
        return this._declaracaoInicial_;
    }

    public void setDeclaracaoInicial(List<?> list)
    {
        for(PDeclaracaoInicial e : this._declaracaoInicial_)
        {
            e.parent(null);
        }
        this._declaracaoInicial_.clear();

        for(Object obj_e : list)
        {
            PDeclaracaoInicial e = (PDeclaracaoInicial) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaracaoInicial_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._it_)
            + toString(this._presents_)
            + toString(this._doisPontos_)
            + toString(this._declaracaoInicial_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._it_ == child)
        {
            this._it_ = null;
            return;
        }

        if(this._presents_ == child)
        {
            this._presents_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        if(this._declaracaoInicial_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._it_ == oldChild)
        {
            setIt((TIt) newChild);
            return;
        }

        if(this._presents_ == oldChild)
        {
            setPresents((TPresents) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        for(ListIterator<PDeclaracaoInicial> i = this._declaracaoInicial_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaracaoInicial) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
