/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ADivisaoInteiraExpMultiplicativa extends PExpMultiplicativa
{
    private PExpMultiplicativa _expMultiplicativa_;
    private TDivisaoInteira _divisaoInteira_;
    private PExpUnaria _expUnaria_;

    public ADivisaoInteiraExpMultiplicativa()
    {
        // Constructor
    }

    public ADivisaoInteiraExpMultiplicativa(
        @SuppressWarnings("hiding") PExpMultiplicativa _expMultiplicativa_,
        @SuppressWarnings("hiding") TDivisaoInteira _divisaoInteira_,
        @SuppressWarnings("hiding") PExpUnaria _expUnaria_)
    {
        // Constructor
        setExpMultiplicativa(_expMultiplicativa_);

        setDivisaoInteira(_divisaoInteira_);

        setExpUnaria(_expUnaria_);

    }

    @Override
    public Object clone()
    {
        return new ADivisaoInteiraExpMultiplicativa(
            cloneNode(this._expMultiplicativa_),
            cloneNode(this._divisaoInteira_),
            cloneNode(this._expUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisaoInteiraExpMultiplicativa(this);
    }

    public PExpMultiplicativa getExpMultiplicativa()
    {
        return this._expMultiplicativa_;
    }

    public void setExpMultiplicativa(PExpMultiplicativa node)
    {
        if(this._expMultiplicativa_ != null)
        {
            this._expMultiplicativa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicativa_ = node;
    }

    public TDivisaoInteira getDivisaoInteira()
    {
        return this._divisaoInteira_;
    }

    public void setDivisaoInteira(TDivisaoInteira node)
    {
        if(this._divisaoInteira_ != null)
        {
            this._divisaoInteira_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divisaoInteira_ = node;
    }

    public PExpUnaria getExpUnaria()
    {
        return this._expUnaria_;
    }

    public void setExpUnaria(PExpUnaria node)
    {
        if(this._expUnaria_ != null)
        {
            this._expUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMultiplicativa_)
            + toString(this._divisaoInteira_)
            + toString(this._expUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMultiplicativa_ == child)
        {
            this._expMultiplicativa_ = null;
            return;
        }

        if(this._divisaoInteira_ == child)
        {
            this._divisaoInteira_ = null;
            return;
        }

        if(this._expUnaria_ == child)
        {
            this._expUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMultiplicativa_ == oldChild)
        {
            setExpMultiplicativa((PExpMultiplicativa) newChild);
            return;
        }

        if(this._divisaoInteira_ == oldChild)
        {
            setDivisaoInteira((TDivisaoInteira) newChild);
            return;
        }

        if(this._expUnaria_ == oldChild)
        {
            setExpUnaria((PExpUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
