/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AElseOpcional extends PElseOpcional
{
    private TOtherwise _otherwise_;
    private TDo _do_;
    private PComandoComposto _comandoComposto_;

    public AElseOpcional()
    {
        // Constructor
    }

    public AElseOpcional(
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PComandoComposto _comandoComposto_)
    {
        // Constructor
        setOtherwise(_otherwise_);

        setDo(_do_);

        setComandoComposto(_comandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new AElseOpcional(
            cloneNode(this._otherwise_),
            cloneNode(this._do_),
            cloneNode(this._comandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseOpcional(this);
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PComandoComposto getComandoComposto()
    {
        return this._comandoComposto_;
    }

    public void setComandoComposto(PComandoComposto node)
    {
        if(this._comandoComposto_ != null)
        {
            this._comandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otherwise_)
            + toString(this._do_)
            + toString(this._comandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._comandoComposto_ == child)
        {
            this._comandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._comandoComposto_ == oldChild)
        {
            setComandoComposto((PComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
