/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AExpXorExpOu extends PExpOu
{
    private PExpXor _expXor_;

    public AExpXorExpOu()
    {
        // Constructor
    }

    public AExpXorExpOu(
        @SuppressWarnings("hiding") PExpXor _expXor_)
    {
        // Constructor
        setExpXor(_expXor_);

    }

    @Override
    public Object clone()
    {
        return new AExpXorExpOu(
            cloneNode(this._expXor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpXorExpOu(this);
    }

    public PExpXor getExpXor()
    {
        return this._expXor_;
    }

    public void setExpXor(PExpXor node)
    {
        if(this._expXor_ != null)
        {
            this._expXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expXor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expXor_ == child)
        {
            this._expXor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expXor_ == oldChild)
        {
            setExpXor((PExpXor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
