/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AExpMultiplicativaExpAditiva extends PExpAditiva
{
    private PExpMultiplicativa _expMultiplicativa_;

    public AExpMultiplicativaExpAditiva()
    {
        // Constructor
    }

    public AExpMultiplicativaExpAditiva(
        @SuppressWarnings("hiding") PExpMultiplicativa _expMultiplicativa_)
    {
        // Constructor
        setExpMultiplicativa(_expMultiplicativa_);

    }

    @Override
    public Object clone()
    {
        return new AExpMultiplicativaExpAditiva(
            cloneNode(this._expMultiplicativa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMultiplicativaExpAditiva(this);
    }

    public PExpMultiplicativa getExpMultiplicativa()
    {
        return this._expMultiplicativa_;
    }

    public void setExpMultiplicativa(PExpMultiplicativa node)
    {
        if(this._expMultiplicativa_ != null)
        {
            this._expMultiplicativa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicativa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMultiplicativa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMultiplicativa_ == child)
        {
            this._expMultiplicativa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMultiplicativa_ == oldChild)
        {
            setExpMultiplicativa((PExpMultiplicativa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
