/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AExpAditivaExpRelacional extends PExpRelacional
{
    private PExpAditiva _expAditiva_;

    public AExpAditivaExpRelacional()
    {
        // Constructor
    }

    public AExpAditivaExpRelacional(
        @SuppressWarnings("hiding") PExpAditiva _expAditiva_)
    {
        // Constructor
        setExpAditiva(_expAditiva_);

    }

    @Override
    public Object clone()
    {
        return new AExpAditivaExpRelacional(
            cloneNode(this._expAditiva_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAditivaExpRelacional(this);
    }

    public PExpAditiva getExpAditiva()
    {
        return this._expAditiva_;
    }

    public void setExpAditiva(PExpAditiva node)
    {
        if(this._expAditiva_ != null)
        {
            this._expAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAditiva_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAditiva_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAditiva_ == child)
        {
            this._expAditiva_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAditiva_ == oldChild)
        {
            setExpAditiva((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
