/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AIgualExpRelacional extends PExpRelacional
{
    private PExpRelacional _expRelacional_;
    private TIgualComparacao _igualComparacao_;
    private PExpAditiva _expAditiva_;

    public AIgualExpRelacional()
    {
        // Constructor
    }

    public AIgualExpRelacional(
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_,
        @SuppressWarnings("hiding") TIgualComparacao _igualComparacao_,
        @SuppressWarnings("hiding") PExpAditiva _expAditiva_)
    {
        // Constructor
        setExpRelacional(_expRelacional_);

        setIgualComparacao(_igualComparacao_);

        setExpAditiva(_expAditiva_);

    }

    @Override
    public Object clone()
    {
        return new AIgualExpRelacional(
            cloneNode(this._expRelacional_),
            cloneNode(this._igualComparacao_),
            cloneNode(this._expAditiva_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualExpRelacional(this);
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    public TIgualComparacao getIgualComparacao()
    {
        return this._igualComparacao_;
    }

    public void setIgualComparacao(TIgualComparacao node)
    {
        if(this._igualComparacao_ != null)
        {
            this._igualComparacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualComparacao_ = node;
    }

    public PExpAditiva getExpAditiva()
    {
        return this._expAditiva_;
    }

    public void setExpAditiva(PExpAditiva node)
    {
        if(this._expAditiva_ != null)
        {
            this._expAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAditiva_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelacional_)
            + toString(this._igualComparacao_)
            + toString(this._expAditiva_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        if(this._igualComparacao_ == child)
        {
            this._igualComparacao_ = null;
            return;
        }

        if(this._expAditiva_ == child)
        {
            this._expAditiva_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        if(this._igualComparacao_ == oldChild)
        {
            setIgualComparacao((TIgualComparacao) newChild);
            return;
        }

        if(this._expAditiva_ == oldChild)
        {
            setExpAditiva((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
