/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AIndexadaVar extends PVar
{
    private TId _id_;
    private TParentesesEsquerda _parentesesEsquerda_;
    private PExp _exp_;
    private final LinkedList<PIndicesVetor> _indicesVetor_ = new LinkedList<PIndicesVetor>();
    private TParentesesDireita _parentesesDireita_;

    public AIndexadaVar()
    {
        // Constructor
    }

    public AIndexadaVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TParentesesEsquerda _parentesesEsquerda_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _indicesVetor_,
        @SuppressWarnings("hiding") TParentesesDireita _parentesesDireita_)
    {
        // Constructor
        setId(_id_);

        setParentesesEsquerda(_parentesesEsquerda_);

        setExp(_exp_);

        setIndicesVetor(_indicesVetor_);

        setParentesesDireita(_parentesesDireita_);

    }

    @Override
    public Object clone()
    {
        return new AIndexadaVar(
            cloneNode(this._id_),
            cloneNode(this._parentesesEsquerda_),
            cloneNode(this._exp_),
            cloneList(this._indicesVetor_),
            cloneNode(this._parentesesDireita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIndexadaVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TParentesesEsquerda getParentesesEsquerda()
    {
        return this._parentesesEsquerda_;
    }

    public void setParentesesEsquerda(TParentesesEsquerda node)
    {
        if(this._parentesesEsquerda_ != null)
        {
            this._parentesesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerda_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PIndicesVetor> getIndicesVetor()
    {
        return this._indicesVetor_;
    }

    public void setIndicesVetor(List<?> list)
    {
        for(PIndicesVetor e : this._indicesVetor_)
        {
            e.parent(null);
        }
        this._indicesVetor_.clear();

        for(Object obj_e : list)
        {
            PIndicesVetor e = (PIndicesVetor) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._indicesVetor_.add(e);
        }
    }

    public TParentesesDireita getParentesesDireita()
    {
        return this._parentesesDireita_;
    }

    public void setParentesesDireita(TParentesesDireita node)
    {
        if(this._parentesesDireita_ != null)
        {
            this._parentesesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._parentesesEsquerda_)
            + toString(this._exp_)
            + toString(this._indicesVetor_)
            + toString(this._parentesesDireita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parentesesEsquerda_ == child)
        {
            this._parentesesEsquerda_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._indicesVetor_.remove(child))
        {
            return;
        }

        if(this._parentesesDireita_ == child)
        {
            this._parentesesDireita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._parentesesEsquerda_ == oldChild)
        {
            setParentesesEsquerda((TParentesesEsquerda) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PIndicesVetor> i = this._indicesVetor_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIndicesVetor) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._parentesesDireita_ == oldChild)
        {
            setParentesesDireita((TParentesesDireita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
