/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AInicializacaoVarivel extends PInicializacaoVarivel
{
    private TIgualAtribuicao _igualAtribuicao_;
    private PValor _valor_;

    public AInicializacaoVarivel()
    {
        // Constructor
    }

    public AInicializacaoVarivel(
        @SuppressWarnings("hiding") TIgualAtribuicao _igualAtribuicao_,
        @SuppressWarnings("hiding") PValor _valor_)
    {
        // Constructor
        setIgualAtribuicao(_igualAtribuicao_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AInicializacaoVarivel(
            cloneNode(this._igualAtribuicao_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInicializacaoVarivel(this);
    }

    public TIgualAtribuicao getIgualAtribuicao()
    {
        return this._igualAtribuicao_;
    }

    public void setIgualAtribuicao(TIgualAtribuicao node)
    {
        if(this._igualAtribuicao_ != null)
        {
            this._igualAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualAtribuicao_ = node;
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._igualAtribuicao_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._igualAtribuicao_ == child)
        {
            this._igualAtribuicao_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._igualAtribuicao_ == oldChild)
        {
            setIgualAtribuicao((TIgualAtribuicao) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
