/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ALacoForComandoComposto extends PComandoComposto
{
    private TConsidering _considering_;
    private PVar _var_;
    private TFrom _from_;
    private PInicio _inicio_;
    private TTo _to_;
    private PFim _fim_;
    private TBy _by_;
    private PIncremento _incremento_;
    private TDo _do_;
    private PComandoComposto _comandoComposto_;

    public ALacoForComandoComposto()
    {
        // Constructor
    }

    public ALacoForComandoComposto(
        @SuppressWarnings("hiding") TConsidering _considering_,
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TFrom _from_,
        @SuppressWarnings("hiding") PInicio _inicio_,
        @SuppressWarnings("hiding") TTo _to_,
        @SuppressWarnings("hiding") PFim _fim_,
        @SuppressWarnings("hiding") TBy _by_,
        @SuppressWarnings("hiding") PIncremento _incremento_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PComandoComposto _comandoComposto_)
    {
        // Constructor
        setConsidering(_considering_);

        setVar(_var_);

        setFrom(_from_);

        setInicio(_inicio_);

        setTo(_to_);

        setFim(_fim_);

        setBy(_by_);

        setIncremento(_incremento_);

        setDo(_do_);

        setComandoComposto(_comandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new ALacoForComandoComposto(
            cloneNode(this._considering_),
            cloneNode(this._var_),
            cloneNode(this._from_),
            cloneNode(this._inicio_),
            cloneNode(this._to_),
            cloneNode(this._fim_),
            cloneNode(this._by_),
            cloneNode(this._incremento_),
            cloneNode(this._do_),
            cloneNode(this._comandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALacoForComandoComposto(this);
    }

    public TConsidering getConsidering()
    {
        return this._considering_;
    }

    public void setConsidering(TConsidering node)
    {
        if(this._considering_ != null)
        {
            this._considering_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._considering_ = node;
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TFrom getFrom()
    {
        return this._from_;
    }

    public void setFrom(TFrom node)
    {
        if(this._from_ != null)
        {
            this._from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._from_ = node;
    }

    public PInicio getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(PInicio node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public TTo getTo()
    {
        return this._to_;
    }

    public void setTo(TTo node)
    {
        if(this._to_ != null)
        {
            this._to_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._to_ = node;
    }

    public PFim getFim()
    {
        return this._fim_;
    }

    public void setFim(PFim node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public TBy getBy()
    {
        return this._by_;
    }

    public void setBy(TBy node)
    {
        if(this._by_ != null)
        {
            this._by_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._by_ = node;
    }

    public PIncremento getIncremento()
    {
        return this._incremento_;
    }

    public void setIncremento(PIncremento node)
    {
        if(this._incremento_ != null)
        {
            this._incremento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._incremento_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PComandoComposto getComandoComposto()
    {
        return this._comandoComposto_;
    }

    public void setComandoComposto(PComandoComposto node)
    {
        if(this._comandoComposto_ != null)
        {
            this._comandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._considering_)
            + toString(this._var_)
            + toString(this._from_)
            + toString(this._inicio_)
            + toString(this._to_)
            + toString(this._fim_)
            + toString(this._by_)
            + toString(this._incremento_)
            + toString(this._do_)
            + toString(this._comandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._considering_ == child)
        {
            this._considering_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._from_ == child)
        {
            this._from_ = null;
            return;
        }

        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._to_ == child)
        {
            this._to_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._by_ == child)
        {
            this._by_ = null;
            return;
        }

        if(this._incremento_ == child)
        {
            this._incremento_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._comandoComposto_ == child)
        {
            this._comandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._considering_ == oldChild)
        {
            setConsidering((TConsidering) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(this._inicio_ == oldChild)
        {
            setInicio((PInicio) newChild);
            return;
        }

        if(this._to_ == oldChild)
        {
            setTo((TTo) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((PFim) newChild);
            return;
        }

        if(this._by_ == oldChild)
        {
            setBy((TBy) newChild);
            return;
        }

        if(this._incremento_ == oldChild)
        {
            setIncremento((PIncremento) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._comandoComposto_ == oldChild)
        {
            setComandoComposto((PComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
