/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ALacoWhileComandoComposto extends PComandoComposto
{
    private TAs _as_;
    private PLongAs _longAs_;
    private TParentesesEsquerda _parentesesEsquerda_;
    private PExp _exp_;
    private TParentesesDireita _parentesesDireita_;
    private TDo _do_;
    private PComandoComposto _comandoComposto_;

    public ALacoWhileComandoComposto()
    {
        // Constructor
    }

    public ALacoWhileComandoComposto(
        @SuppressWarnings("hiding") TAs _as_,
        @SuppressWarnings("hiding") PLongAs _longAs_,
        @SuppressWarnings("hiding") TParentesesEsquerda _parentesesEsquerda_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParentesesDireita _parentesesDireita_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PComandoComposto _comandoComposto_)
    {
        // Constructor
        setAs(_as_);

        setLongAs(_longAs_);

        setParentesesEsquerda(_parentesesEsquerda_);

        setExp(_exp_);

        setParentesesDireita(_parentesesDireita_);

        setDo(_do_);

        setComandoComposto(_comandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new ALacoWhileComandoComposto(
            cloneNode(this._as_),
            cloneNode(this._longAs_),
            cloneNode(this._parentesesEsquerda_),
            cloneNode(this._exp_),
            cloneNode(this._parentesesDireita_),
            cloneNode(this._do_),
            cloneNode(this._comandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALacoWhileComandoComposto(this);
    }

    public TAs getAs()
    {
        return this._as_;
    }

    public void setAs(TAs node)
    {
        if(this._as_ != null)
        {
            this._as_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._as_ = node;
    }

    public PLongAs getLongAs()
    {
        return this._longAs_;
    }

    public void setLongAs(PLongAs node)
    {
        if(this._longAs_ != null)
        {
            this._longAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._longAs_ = node;
    }

    public TParentesesEsquerda getParentesesEsquerda()
    {
        return this._parentesesEsquerda_;
    }

    public void setParentesesEsquerda(TParentesesEsquerda node)
    {
        if(this._parentesesEsquerda_ != null)
        {
            this._parentesesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerda_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParentesesDireita getParentesesDireita()
    {
        return this._parentesesDireita_;
    }

    public void setParentesesDireita(TParentesesDireita node)
    {
        if(this._parentesesDireita_ != null)
        {
            this._parentesesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireita_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PComandoComposto getComandoComposto()
    {
        return this._comandoComposto_;
    }

    public void setComandoComposto(PComandoComposto node)
    {
        if(this._comandoComposto_ != null)
        {
            this._comandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._as_)
            + toString(this._longAs_)
            + toString(this._parentesesEsquerda_)
            + toString(this._exp_)
            + toString(this._parentesesDireita_)
            + toString(this._do_)
            + toString(this._comandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._as_ == child)
        {
            this._as_ = null;
            return;
        }

        if(this._longAs_ == child)
        {
            this._longAs_ = null;
            return;
        }

        if(this._parentesesEsquerda_ == child)
        {
            this._parentesesEsquerda_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parentesesDireita_ == child)
        {
            this._parentesesDireita_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._comandoComposto_ == child)
        {
            this._comandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._as_ == oldChild)
        {
            setAs((TAs) newChild);
            return;
        }

        if(this._longAs_ == oldChild)
        {
            setLongAs((PLongAs) newChild);
            return;
        }

        if(this._parentesesEsquerda_ == oldChild)
        {
            setParentesesEsquerda((TParentesesEsquerda) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parentesesDireita_ == oldChild)
        {
            setParentesesDireita((TParentesesDireita) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._comandoComposto_ == oldChild)
        {
            setComandoComposto((PComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
