/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AListaVars extends PListaVars
{
    private PVar _var_;
    private final LinkedList<PVirgulasVars> _virgulasVars_ = new LinkedList<PVirgulasVars>();

    public AListaVars()
    {
        // Constructor
    }

    public AListaVars(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") List<?> _virgulasVars_)
    {
        // Constructor
        setVar(_var_);

        setVirgulasVars(_virgulasVars_);

    }

    @Override
    public Object clone()
    {
        return new AListaVars(
            cloneNode(this._var_),
            cloneList(this._virgulasVars_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVars(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public LinkedList<PVirgulasVars> getVirgulasVars()
    {
        return this._virgulasVars_;
    }

    public void setVirgulasVars(List<?> list)
    {
        for(PVirgulasVars e : this._virgulasVars_)
        {
            e.parent(null);
        }
        this._virgulasVars_.clear();

        for(Object obj_e : list)
        {
            PVirgulasVars e = (PVirgulasVars) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._virgulasVars_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._virgulasVars_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._virgulasVars_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        for(ListIterator<PVirgulasVars> i = this._virgulasVars_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVirgulasVars) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
