/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AListaExps extends PListaExps
{
    private PExp _exp_;
    private final LinkedList<PVirgulasExps> _virgulasExps_ = new LinkedList<PVirgulasExps>();

    public AListaExps()
    {
        // Constructor
    }

    public AListaExps(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _virgulasExps_)
    {
        // Constructor
        setExp(_exp_);

        setVirgulasExps(_virgulasExps_);

    }

    @Override
    public Object clone()
    {
        return new AListaExps(
            cloneNode(this._exp_),
            cloneList(this._virgulasExps_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExps(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PVirgulasExps> getVirgulasExps()
    {
        return this._virgulasExps_;
    }

    public void setVirgulasExps(List<?> list)
    {
        for(PVirgulasExps e : this._virgulasExps_)
        {
            e.parent(null);
        }
        this._virgulasExps_.clear();

        for(Object obj_e : list)
        {
            PVirgulasExps e = (PVirgulasExps) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._virgulasExps_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virgulasExps_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virgulasExps_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PVirgulasExps> i = this._virgulasExps_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVirgulasExps) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
