/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ALongAs extends PLongAs
{
    private TLong _long_;
    private TAs _as_;

    public ALongAs()
    {
        // Constructor
    }

    public ALongAs(
        @SuppressWarnings("hiding") TLong _long_,
        @SuppressWarnings("hiding") TAs _as_)
    {
        // Constructor
        setLong(_long_);

        setAs(_as_);

    }

    @Override
    public Object clone()
    {
        return new ALongAs(
            cloneNode(this._long_),
            cloneNode(this._as_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALongAs(this);
    }

    public TLong getLong()
    {
        return this._long_;
    }

    public void setLong(TLong node)
    {
        if(this._long_ != null)
        {
            this._long_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._long_ = node;
    }

    public TAs getAs()
    {
        return this._as_;
    }

    public void setAs(TAs node)
    {
        if(this._as_ != null)
        {
            this._as_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._as_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._long_)
            + toString(this._as_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._long_ == child)
        {
            this._long_ = null;
            return;
        }

        if(this._as_ == child)
        {
            this._as_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._long_ == oldChild)
        {
            setLong((TLong) newChild);
            return;
        }

        if(this._as_ == oldChild)
        {
            setAs((TAs) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
