/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExpRelacional extends PExpRelacional
{
    private PExpRelacional _expRelacional_;
    private TMaior _maior_;
    private PExpAditiva _expAditiva_;

    public AMaiorExpRelacional()
    {
        // Constructor
    }

    public AMaiorExpRelacional(
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExpAditiva _expAditiva_)
    {
        // Constructor
        setExpRelacional(_expRelacional_);

        setMaior(_maior_);

        setExpAditiva(_expAditiva_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExpRelacional(
            cloneNode(this._expRelacional_),
            cloneNode(this._maior_),
            cloneNode(this._expAditiva_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExpRelacional(this);
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExpAditiva getExpAditiva()
    {
        return this._expAditiva_;
    }

    public void setExpAditiva(PExpAditiva node)
    {
        if(this._expAditiva_ != null)
        {
            this._expAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAditiva_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelacional_)
            + toString(this._maior_)
            + toString(this._expAditiva_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._expAditiva_ == child)
        {
            this._expAditiva_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._expAditiva_ == oldChild)
        {
            setExpAditiva((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
