/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AMenorExpRelacional extends PExpRelacional
{
    private PExpRelacional _expRelacional_;
    private TMenor _menor_;
    private PExpAditiva _expAditiva_;

    public AMenorExpRelacional()
    {
        // Constructor
    }

    public AMenorExpRelacional(
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PExpAditiva _expAditiva_)
    {
        // Constructor
        setExpRelacional(_expRelacional_);

        setMenor(_menor_);

        setExpAditiva(_expAditiva_);

    }

    @Override
    public Object clone()
    {
        return new AMenorExpRelacional(
            cloneNode(this._expRelacional_),
            cloneNode(this._menor_),
            cloneNode(this._expAditiva_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExpRelacional(this);
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PExpAditiva getExpAditiva()
    {
        return this._expAditiva_;
    }

    public void setExpAditiva(PExpAditiva node)
    {
        if(this._expAditiva_ != null)
        {
            this._expAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAditiva_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelacional_)
            + toString(this._menor_)
            + toString(this._expAditiva_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._expAditiva_ == child)
        {
            this._expAditiva_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._expAditiva_ == oldChild)
        {
            setExpAditiva((PExpAditiva) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
