/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AMenosUnarioExpUnaria extends PExpUnaria
{
    private TSubtracao _subtracao_;
    private PExpUnaria _expUnaria_;

    public AMenosUnarioExpUnaria()
    {
        // Constructor
    }

    public AMenosUnarioExpUnaria(
        @SuppressWarnings("hiding") TSubtracao _subtracao_,
        @SuppressWarnings("hiding") PExpUnaria _expUnaria_)
    {
        // Constructor
        setSubtracao(_subtracao_);

        setExpUnaria(_expUnaria_);

    }

    @Override
    public Object clone()
    {
        return new AMenosUnarioExpUnaria(
            cloneNode(this._subtracao_),
            cloneNode(this._expUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosUnarioExpUnaria(this);
    }

    public TSubtracao getSubtracao()
    {
        return this._subtracao_;
    }

    public void setSubtracao(TSubtracao node)
    {
        if(this._subtracao_ != null)
        {
            this._subtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subtracao_ = node;
    }

    public PExpUnaria getExpUnaria()
    {
        return this._expUnaria_;
    }

    public void setExpUnaria(PExpUnaria node)
    {
        if(this._expUnaria_ != null)
        {
            this._expUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subtracao_)
            + toString(this._expUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subtracao_ == child)
        {
            this._subtracao_ = null;
            return;
        }

        if(this._expUnaria_ == child)
        {
            this._expUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subtracao_ == oldChild)
        {
            setSubtracao((TSubtracao) newChild);
            return;
        }

        if(this._expUnaria_ == oldChild)
        {
            setExpUnaria((PExpUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
