/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ANumberValor extends PValor
{
    private TValorNumber _valorNumber_;

    public ANumberValor()
    {
        // Constructor
    }

    public ANumberValor(
        @SuppressWarnings("hiding") TValorNumber _valorNumber_)
    {
        // Constructor
        setValorNumber(_valorNumber_);

    }

    @Override
    public Object clone()
    {
        return new ANumberValor(
            cloneNode(this._valorNumber_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumberValor(this);
    }

    public TValorNumber getValorNumber()
    {
        return this._valorNumber_;
    }

    public void setValorNumber(TValorNumber node)
    {
        if(this._valorNumber_ != null)
        {
            this._valorNumber_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorNumber_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorNumber_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorNumber_ == child)
        {
            this._valorNumber_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorNumber_ == oldChild)
        {
            setValorNumber((TValorNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
