/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AOuExclusivoExpXor extends PExpXor
{
    private PExpXor _expXor_;
    private TXor _xor_;
    private PExpE _expE_;

    public AOuExclusivoExpXor()
    {
        // Constructor
    }

    public AOuExclusivoExpXor(
        @SuppressWarnings("hiding") PExpXor _expXor_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PExpE _expE_)
    {
        // Constructor
        setExpXor(_expXor_);

        setXor(_xor_);

        setExpE(_expE_);

    }

    @Override
    public Object clone()
    {
        return new AOuExclusivoExpXor(
            cloneNode(this._expXor_),
            cloneNode(this._xor_),
            cloneNode(this._expE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuExclusivoExpXor(this);
    }

    public PExpXor getExpXor()
    {
        return this._expXor_;
    }

    public void setExpXor(PExpXor node)
    {
        if(this._expXor_ != null)
        {
            this._expXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXor_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expXor_)
            + toString(this._xor_)
            + toString(this._expE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expXor_ == child)
        {
            this._expXor_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expXor_ == oldChild)
        {
            setExpXor((PExpXor) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
