/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AOuLogicoExpOu extends PExpOu
{
    private PExpOu _expOu_;
    private TOr _or_;
    private PExpXor _expXor_;

    public AOuLogicoExpOu()
    {
        // Constructor
    }

    public AOuLogicoExpOu(
        @SuppressWarnings("hiding") PExpOu _expOu_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PExpXor _expXor_)
    {
        // Constructor
        setExpOu(_expOu_);

        setOr(_or_);

        setExpXor(_expXor_);

    }

    @Override
    public Object clone()
    {
        return new AOuLogicoExpOu(
            cloneNode(this._expOu_),
            cloneNode(this._or_),
            cloneNode(this._expXor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuLogicoExpOu(this);
    }

    public PExpOu getExpOu()
    {
        return this._expOu_;
    }

    public void setExpOu(PExpOu node)
    {
        if(this._expOu_ != null)
        {
            this._expOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOu_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PExpXor getExpXor()
    {
        return this._expXor_;
    }

    public void setExpXor(PExpXor node)
    {
        if(this._expXor_ != null)
        {
            this._expXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expXor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOu_)
            + toString(this._or_)
            + toString(this._expXor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOu_ == child)
        {
            this._expOu_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._expXor_ == child)
        {
            this._expXor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOu_ == oldChild)
        {
            setExpOu((PExpOu) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._expXor_ == oldChild)
        {
            setExpXor((PExpXor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
