/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AParentesesExpPrimaria extends PExpPrimaria
{
    private TParentesesEsquerda _parentesesEsquerda_;
    private PExp _exp_;
    private TParentesesDireita _parentesesDireita_;

    public AParentesesExpPrimaria()
    {
        // Constructor
    }

    public AParentesesExpPrimaria(
        @SuppressWarnings("hiding") TParentesesEsquerda _parentesesEsquerda_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParentesesDireita _parentesesDireita_)
    {
        // Constructor
        setParentesesEsquerda(_parentesesEsquerda_);

        setExp(_exp_);

        setParentesesDireita(_parentesesDireita_);

    }

    @Override
    public Object clone()
    {
        return new AParentesesExpPrimaria(
            cloneNode(this._parentesesEsquerda_),
            cloneNode(this._exp_),
            cloneNode(this._parentesesDireita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesesExpPrimaria(this);
    }

    public TParentesesEsquerda getParentesesEsquerda()
    {
        return this._parentesesEsquerda_;
    }

    public void setParentesesEsquerda(TParentesesEsquerda node)
    {
        if(this._parentesesEsquerda_ != null)
        {
            this._parentesesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerda_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParentesesDireita getParentesesDireita()
    {
        return this._parentesesDireita_;
    }

    public void setParentesesDireita(TParentesesDireita node)
    {
        if(this._parentesesDireita_ != null)
        {
            this._parentesesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parentesesEsquerda_)
            + toString(this._exp_)
            + toString(this._parentesesDireita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parentesesEsquerda_ == child)
        {
            this._parentesesEsquerda_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parentesesDireita_ == child)
        {
            this._parentesesDireita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parentesesEsquerda_ == oldChild)
        {
            setParentesesEsquerda((TParentesesEsquerda) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parentesesDireita_ == oldChild)
        {
            setParentesesDireita((TParentesesDireita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
