/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AShowComandoSimples extends PComandoSimples
{
    private TShow _show_;
    private TParentesesEsquerda _parentesesEsquerda_;
    private PListaExps _listaExps_;
    private TParentesesDireita _parentesesDireita_;
    private TPontoVirgula _pontoVirgula_;

    public AShowComandoSimples()
    {
        // Constructor
    }

    public AShowComandoSimples(
        @SuppressWarnings("hiding") TShow _show_,
        @SuppressWarnings("hiding") TParentesesEsquerda _parentesesEsquerda_,
        @SuppressWarnings("hiding") PListaExps _listaExps_,
        @SuppressWarnings("hiding") TParentesesDireita _parentesesDireita_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setShow(_show_);

        setParentesesEsquerda(_parentesesEsquerda_);

        setListaExps(_listaExps_);

        setParentesesDireita(_parentesesDireita_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AShowComandoSimples(
            cloneNode(this._show_),
            cloneNode(this._parentesesEsquerda_),
            cloneNode(this._listaExps_),
            cloneNode(this._parentesesDireita_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShowComandoSimples(this);
    }

    public TShow getShow()
    {
        return this._show_;
    }

    public void setShow(TShow node)
    {
        if(this._show_ != null)
        {
            this._show_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._show_ = node;
    }

    public TParentesesEsquerda getParentesesEsquerda()
    {
        return this._parentesesEsquerda_;
    }

    public void setParentesesEsquerda(TParentesesEsquerda node)
    {
        if(this._parentesesEsquerda_ != null)
        {
            this._parentesesEsquerda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesEsquerda_ = node;
    }

    public PListaExps getListaExps()
    {
        return this._listaExps_;
    }

    public void setListaExps(PListaExps node)
    {
        if(this._listaExps_ != null)
        {
            this._listaExps_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExps_ = node;
    }

    public TParentesesDireita getParentesesDireita()
    {
        return this._parentesesDireita_;
    }

    public void setParentesesDireita(TParentesesDireita node)
    {
        if(this._parentesesDireita_ != null)
        {
            this._parentesesDireita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentesesDireita_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._show_)
            + toString(this._parentesesEsquerda_)
            + toString(this._listaExps_)
            + toString(this._parentesesDireita_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._show_ == child)
        {
            this._show_ = null;
            return;
        }

        if(this._parentesesEsquerda_ == child)
        {
            this._parentesesEsquerda_ = null;
            return;
        }

        if(this._listaExps_ == child)
        {
            this._listaExps_ = null;
            return;
        }

        if(this._parentesesDireita_ == child)
        {
            this._parentesesDireita_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._show_ == oldChild)
        {
            setShow((TShow) newChild);
            return;
        }

        if(this._parentesesEsquerda_ == oldChild)
        {
            setParentesesEsquerda((TParentesesEsquerda) newChild);
            return;
        }

        if(this._listaExps_ == oldChild)
        {
            setListaExps((PListaExps) newChild);
            return;
        }

        if(this._parentesesDireita_ == oldChild)
        {
            setParentesesDireita((TParentesesDireita) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
