/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExpAditiva extends PExpAditiva
{
    private PExpAditiva _expAditiva_;
    private TSoma _soma_;
    private PExpMultiplicativa _expMultiplicativa_;

    public ASomaExpAditiva()
    {
        // Constructor
    }

    public ASomaExpAditiva(
        @SuppressWarnings("hiding") PExpAditiva _expAditiva_,
        @SuppressWarnings("hiding") TSoma _soma_,
        @SuppressWarnings("hiding") PExpMultiplicativa _expMultiplicativa_)
    {
        // Constructor
        setExpAditiva(_expAditiva_);

        setSoma(_soma_);

        setExpMultiplicativa(_expMultiplicativa_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpAditiva(
            cloneNode(this._expAditiva_),
            cloneNode(this._soma_),
            cloneNode(this._expMultiplicativa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpAditiva(this);
    }

    public PExpAditiva getExpAditiva()
    {
        return this._expAditiva_;
    }

    public void setExpAditiva(PExpAditiva node)
    {
        if(this._expAditiva_ != null)
        {
            this._expAditiva_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAditiva_ = node;
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PExpMultiplicativa getExpMultiplicativa()
    {
        return this._expMultiplicativa_;
    }

    public void setExpMultiplicativa(PExpMultiplicativa node)
    {
        if(this._expMultiplicativa_ != null)
        {
            this._expMultiplicativa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicativa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAditiva_)
            + toString(this._soma_)
            + toString(this._expMultiplicativa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAditiva_ == child)
        {
            this._expAditiva_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._expMultiplicativa_ == child)
        {
            this._expMultiplicativa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAditiva_ == oldChild)
        {
            setExpAditiva((PExpAditiva) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        if(this._expMultiplicativa_ == oldChild)
        {
            setExpMultiplicativa((PExpMultiplicativa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
