/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ASymbolValor extends PValor
{
    private TValorSymbol _valorSymbol_;

    public ASymbolValor()
    {
        // Constructor
    }

    public ASymbolValor(
        @SuppressWarnings("hiding") TValorSymbol _valorSymbol_)
    {
        // Constructor
        setValorSymbol(_valorSymbol_);

    }

    @Override
    public Object clone()
    {
        return new ASymbolValor(
            cloneNode(this._valorSymbol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASymbolValor(this);
    }

    public TValorSymbol getValorSymbol()
    {
        return this._valorSymbol_;
    }

    public void setValorSymbol(TValorSymbol node)
    {
        if(this._valorSymbol_ != null)
        {
            this._valorSymbol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorSymbol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorSymbol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorSymbol_ == child)
        {
            this._valorSymbol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorSymbol_ == oldChild)
        {
            setValorSymbol((TValorSymbol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
