/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelDeclaracaoBloco extends PDeclaracaoBloco
{
    private TAlterable _alterable_;
    private PTipo _tipo_;
    private TId _id_;
    private PInicializacaoVarivel _inicializacaoVarivel_;
    private TPontoVirgula _pontoVirgula_;

    public AVariavelDeclaracaoBloco()
    {
        // Constructor
    }

    public AVariavelDeclaracaoBloco(
        @SuppressWarnings("hiding") TAlterable _alterable_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PInicializacaoVarivel _inicializacaoVarivel_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setAlterable(_alterable_);

        setTipo(_tipo_);

        setId(_id_);

        setInicializacaoVarivel(_inicializacaoVarivel_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelDeclaracaoBloco(
            cloneNode(this._alterable_),
            cloneNode(this._tipo_),
            cloneNode(this._id_),
            cloneNode(this._inicializacaoVarivel_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelDeclaracaoBloco(this);
    }

    public TAlterable getAlterable()
    {
        return this._alterable_;
    }

    public void setAlterable(TAlterable node)
    {
        if(this._alterable_ != null)
        {
            this._alterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alterable_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PInicializacaoVarivel getInicializacaoVarivel()
    {
        return this._inicializacaoVarivel_;
    }

    public void setInicializacaoVarivel(PInicializacaoVarivel node)
    {
        if(this._inicializacaoVarivel_ != null)
        {
            this._inicializacaoVarivel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializacaoVarivel_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alterable_)
            + toString(this._tipo_)
            + toString(this._id_)
            + toString(this._inicializacaoVarivel_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alterable_ == child)
        {
            this._alterable_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._inicializacaoVarivel_ == child)
        {
            this._inicializacaoVarivel_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alterable_ == oldChild)
        {
            setAlterable((TAlterable) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._inicializacaoVarivel_ == oldChild)
        {
            setInicializacaoVarivel((PInicializacaoVarivel) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
