/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TThat2 extends Token
{
    public TThat2()
    {
        super.setText("that");
    }

    public TThat2(int line, int pos)
    {
        super.setText("that");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThat2(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThat2(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThat2 text.");
    }
}
