/* This file was generated by SableCC (http://www.sablecc.org/). */

package tipo.node;

import java.util.*;
import tipo.analysis.*;

@SuppressWarnings("nls")
public final class AArInicioAInicio extends PAInicio
{
    private final LinkedList<PADeclaracao> _arDeclaracoes_ = new LinkedList<PADeclaracao>();

    public AArInicioAInicio()
    {
        // Constructor
    }

    public AArInicioAInicio(
        @SuppressWarnings("hiding") List<?> _arDeclaracoes_)
    {
        // Constructor
        setArDeclaracoes(_arDeclaracoes_);

    }

    @Override
    public Object clone()
    {
        return new AArInicioAInicio(
            cloneList(this._arDeclaracoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArInicioAInicio(this);
    }

    public LinkedList<PADeclaracao> getArDeclaracoes()
    {
        return this._arDeclaracoes_;
    }

    public void setArDeclaracoes(List<?> list)
    {
        for(PADeclaracao e : this._arDeclaracoes_)
        {
            e.parent(null);
        }
        this._arDeclaracoes_.clear();

        for(Object obj_e : list)
        {
            PADeclaracao e = (PADeclaracao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._arDeclaracoes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arDeclaracoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arDeclaracoes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PADeclaracao> i = this._arDeclaracoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PADeclaracao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
