/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.analysis;

import java.util.*;
import prolixa.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAPrograma(AAPrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAADeclaracoes(AADeclaracoes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAComandos(AAComandos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAVarADeclaracao(AAVarADeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAVarInitADeclaracao(AAVarInitADeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAConstADeclaracao(AAConstADeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAVetorADeclaracao(AAVetorADeclaracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAANumberATipo(AANumberATipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAnswerATipo(AAAnswerATipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAASymbolATipo(AASymbolATipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAIfAComando(AAIfAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAWhileAComando(AAWhileAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAForAComando(AAForAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAtribAComando(AAAtribAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAtribConstAComando(AAAtribConstAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAACaptureAComando(AACaptureAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAShowAComando(AAShowAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAbandonAComando(AAAbandonAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAContinueAComando(AAContinueAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAABlocoAComando(AABlocoAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAListaVars(AAListaVars node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAListaExps(AAListaExps node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAASimplesAVar(AASimplesAVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAIndexadaAVar(AAIndexadaAVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAOrAExp(AAOrAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAXorAExp(AAXorAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAndAExp(AAAndAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAIgualAExp(AAIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAADiferenteAExp(AADiferenteAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMenorIgualAExp(AAMenorIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMaiorIgualAExp(AAMaiorIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMenorAExp(AAMenorAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMaiorAExp(AAMaiorAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAASomaAExp(AASomaAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAASubtracaoAExp(AASubtracaoAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMultAExp(AAMultAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAADivAExp(AADivAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAADivIntAExp(AADivIntAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAMenosUnarioAExp(AAMenosUnarioAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAANegacaoAExp(AANegacaoAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAVarAExp(AAVarAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAASymbolAExp(AASymbolAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAAnswerAExp(AAAnswerAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAANumberAExp(AANumberAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAStringAExp(AAStringAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentario(TComentario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThis(TThis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIs(TIs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProgram(TProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIt(TIt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPresents(TPresents node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLet(TLet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUs(TUs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBegin(TBegin node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThat(TThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWould(TWould node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBe(TBe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAll(TAll node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlterable(TAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUnalterable(TUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVector(TVector node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOf(TOf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTX(TX node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSymbol(TSymbol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnswer(TAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorSymbol(TValorSymbol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorNumber(TValorNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorAnswer(TValorAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCapture(TCapture node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTShow(TShow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTJust(TJust node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCase(TCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThat2(TThat2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOtherwise(TOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDo(TDo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAs(TAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLong(TLong node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConsidering(TConsidering node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFrom(TFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTo(TTo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBy(TBy node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbandon(TAbandon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGo(TGo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNext(TNext node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIteration(TIteration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgualAtribuicao(TIgualAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSubtracao(TSubtracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMultiplicacao(TMultiplicacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivisao(TDivisao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivisaoInteira(TDivisaoInteira node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgualComparacao(TIgualComparacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNaoIgual(TNaoIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTXor(TXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentesesEsquerda(TParentesesEsquerda node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentesesDireita(TParentesesDireita node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchetesEsquerda(TColchetesEsquerda node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchetesDireita(TColchetesDireita node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspacos(TEspacos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNovasLinhas(TNovasLinhas node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
