/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.analysis;

import java.util.*;
import prolixa.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPAPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAAPrograma(AAPrograma node)
    {
        defaultIn(node);
    }

    public void outAAPrograma(AAPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAPrograma(AAPrograma node)
    {
        inAAPrograma(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getDeclaracoes() != null)
        {
            node.getDeclaracoes().apply(this);
        }
        if(node.getComandos() != null)
        {
            node.getComandos().apply(this);
        }
        outAAPrograma(node);
    }

    public void inAADeclaracoes(AADeclaracoes node)
    {
        defaultIn(node);
    }

    public void outAADeclaracoes(AADeclaracoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAADeclaracoes(AADeclaracoes node)
    {
        inAADeclaracoes(node);
        {
            List<PADeclaracao> copy = new ArrayList<PADeclaracao>(node.getDeclaracoes());
            for(PADeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outAADeclaracoes(node);
    }

    public void inAAComandos(AAComandos node)
    {
        defaultIn(node);
    }

    public void outAAComandos(AAComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAComandos(AAComandos node)
    {
        inAAComandos(node);
        {
            List<PAComando> copy = new ArrayList<PAComando>(node.getComandos());
            for(PAComando e : copy)
            {
                e.apply(this);
            }
        }
        outAAComandos(node);
    }

    public void inAAVarADeclaracao(AAVarADeclaracao node)
    {
        defaultIn(node);
    }

    public void outAAVarADeclaracao(AAVarADeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAVarADeclaracao(AAVarADeclaracao node)
    {
        inAAVarADeclaracao(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        outAAVarADeclaracao(node);
    }

    public void inAAVarInitADeclaracao(AAVarInitADeclaracao node)
    {
        defaultIn(node);
    }

    public void outAAVarInitADeclaracao(AAVarInitADeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAVarInitADeclaracao(AAVarInitADeclaracao node)
    {
        inAAVarInitADeclaracao(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getInit() != null)
        {
            node.getInit().apply(this);
        }
        outAAVarInitADeclaracao(node);
    }

    public void inAAConstADeclaracao(AAConstADeclaracao node)
    {
        defaultIn(node);
    }

    public void outAAConstADeclaracao(AAConstADeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAConstADeclaracao(AAConstADeclaracao node)
    {
        inAAConstADeclaracao(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getInit() != null)
        {
            node.getInit().apply(this);
        }
        outAAConstADeclaracao(node);
    }

    public void inAAVetorADeclaracao(AAVetorADeclaracao node)
    {
        defaultIn(node);
    }

    public void outAAVetorADeclaracao(AAVetorADeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAVetorADeclaracao(AAVetorADeclaracao node)
    {
        inAAVetorADeclaracao(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getTamanho() != null)
        {
            node.getTamanho().apply(this);
        }
        if(node.getDimensoes() != null)
        {
            node.getDimensoes().apply(this);
        }
        outAAVetorADeclaracao(node);
    }

    public void inAANumberATipo(AANumberATipo node)
    {
        defaultIn(node);
    }

    public void outAANumberATipo(AANumberATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAANumberATipo(AANumberATipo node)
    {
        inAANumberATipo(node);
        outAANumberATipo(node);
    }

    public void inAAAnswerATipo(AAAnswerATipo node)
    {
        defaultIn(node);
    }

    public void outAAAnswerATipo(AAAnswerATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAnswerATipo(AAAnswerATipo node)
    {
        inAAAnswerATipo(node);
        outAAAnswerATipo(node);
    }

    public void inAASymbolATipo(AASymbolATipo node)
    {
        defaultIn(node);
    }

    public void outAASymbolATipo(AASymbolATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAASymbolATipo(AASymbolATipo node)
    {
        inAASymbolATipo(node);
        outAASymbolATipo(node);
    }

    public void inAAIfAComando(AAIfAComando node)
    {
        defaultIn(node);
    }

    public void outAAIfAComando(AAIfAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAIfAComando(AAIfAComando node)
    {
        inAAIfAComando(node);
        if(node.getCondicao() != null)
        {
            node.getCondicao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAAIfAComando(node);
    }

    public void inAAWhileAComando(AAWhileAComando node)
    {
        defaultIn(node);
    }

    public void outAAWhileAComando(AAWhileAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAWhileAComando(AAWhileAComando node)
    {
        inAAWhileAComando(node);
        if(node.getCondicao() != null)
        {
            node.getCondicao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAAWhileAComando(node);
    }

    public void inAAForAComando(AAForAComando node)
    {
        defaultIn(node);
    }

    public void outAAForAComando(AAForAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAForAComando(AAForAComando node)
    {
        inAAForAComando(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        if(node.getIncremento() != null)
        {
            node.getIncremento().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAAForAComando(node);
    }

    public void inAAAtribAComando(AAAtribAComando node)
    {
        defaultIn(node);
    }

    public void outAAAtribAComando(AAAtribAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAtribAComando(AAAtribAComando node)
    {
        inAAAtribAComando(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAAAtribAComando(node);
    }

    public void inAAAtribConstAComando(AAAtribConstAComando node)
    {
        defaultIn(node);
    }

    public void outAAAtribConstAComando(AAAtribConstAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAtribConstAComando(AAAtribConstAComando node)
    {
        inAAAtribConstAComando(node);
        if(node.getConstante() != null)
        {
            node.getConstante().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAAAtribConstAComando(node);
    }

    public void inAACaptureAComando(AACaptureAComando node)
    {
        defaultIn(node);
    }

    public void outAACaptureAComando(AACaptureAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAACaptureAComando(AACaptureAComando node)
    {
        inAACaptureAComando(node);
        if(node.getVariaveis() != null)
        {
            node.getVariaveis().apply(this);
        }
        outAACaptureAComando(node);
    }

    public void inAAShowAComando(AAShowAComando node)
    {
        defaultIn(node);
    }

    public void outAAShowAComando(AAShowAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAShowAComando(AAShowAComando node)
    {
        inAAShowAComando(node);
        if(node.getExpressoes() != null)
        {
            node.getExpressoes().apply(this);
        }
        outAAShowAComando(node);
    }

    public void inAAAbandonAComando(AAAbandonAComando node)
    {
        defaultIn(node);
    }

    public void outAAAbandonAComando(AAAbandonAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAbandonAComando(AAAbandonAComando node)
    {
        inAAAbandonAComando(node);
        outAAAbandonAComando(node);
    }

    public void inAAContinueAComando(AAContinueAComando node)
    {
        defaultIn(node);
    }

    public void outAAContinueAComando(AAContinueAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAContinueAComando(AAContinueAComando node)
    {
        inAAContinueAComando(node);
        outAAContinueAComando(node);
    }

    public void inAABlocoAComando(AABlocoAComando node)
    {
        defaultIn(node);
    }

    public void outAABlocoAComando(AABlocoAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAABlocoAComando(AABlocoAComando node)
    {
        inAABlocoAComando(node);
        {
            List<PADeclaracao> copy = new ArrayList<PADeclaracao>(node.getDeclaracoes());
            for(PADeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PAComando> copy = new ArrayList<PAComando>(node.getComandos());
            for(PAComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getElseCmd() != null)
        {
            node.getElseCmd().apply(this);
        }
        outAABlocoAComando(node);
    }

    public void inAAListaVars(AAListaVars node)
    {
        defaultIn(node);
    }

    public void outAAListaVars(AAListaVars node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAListaVars(AAListaVars node)
    {
        inAAListaVars(node);
        if(node.getPrimeira() != null)
        {
            node.getPrimeira().apply(this);
        }
        {
            List<PAVar> copy = new ArrayList<PAVar>(node.getResto());
            for(PAVar e : copy)
            {
                e.apply(this);
            }
        }
        outAAListaVars(node);
    }

    public void inAAListaExps(AAListaExps node)
    {
        defaultIn(node);
    }

    public void outAAListaExps(AAListaExps node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAListaExps(AAListaExps node)
    {
        inAAListaExps(node);
        if(node.getPrimeira() != null)
        {
            node.getPrimeira().apply(this);
        }
        {
            List<PAExp> copy = new ArrayList<PAExp>(node.getResto());
            for(PAExp e : copy)
            {
                e.apply(this);
            }
        }
        outAAListaExps(node);
    }

    public void inAASimplesAVar(AASimplesAVar node)
    {
        defaultIn(node);
    }

    public void outAASimplesAVar(AASimplesAVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAASimplesAVar(AASimplesAVar node)
    {
        inAASimplesAVar(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        outAASimplesAVar(node);
    }

    public void inAAIndexadaAVar(AAIndexadaAVar node)
    {
        defaultIn(node);
    }

    public void outAAIndexadaAVar(AAIndexadaAVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAIndexadaAVar(AAIndexadaAVar node)
    {
        inAAIndexadaAVar(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getIndice() != null)
        {
            node.getIndice().apply(this);
        }
        {
            List<PAExp> copy = new ArrayList<PAExp>(node.getOutrosIndices());
            for(PAExp e : copy)
            {
                e.apply(this);
            }
        }
        outAAIndexadaAVar(node);
    }

    public void inAAOrAExp(AAOrAExp node)
    {
        defaultIn(node);
    }

    public void outAAOrAExp(AAOrAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAOrAExp(AAOrAExp node)
    {
        inAAOrAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAOrAExp(node);
    }

    public void inAAXorAExp(AAXorAExp node)
    {
        defaultIn(node);
    }

    public void outAAXorAExp(AAXorAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAXorAExp(AAXorAExp node)
    {
        inAAXorAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAXorAExp(node);
    }

    public void inAAAndAExp(AAAndAExp node)
    {
        defaultIn(node);
    }

    public void outAAAndAExp(AAAndAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAndAExp(AAAndAExp node)
    {
        inAAAndAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAAndAExp(node);
    }

    public void inAAIgualAExp(AAIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAAIgualAExp(AAIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAIgualAExp(AAIgualAExp node)
    {
        inAAIgualAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAIgualAExp(node);
    }

    public void inAADiferenteAExp(AADiferenteAExp node)
    {
        defaultIn(node);
    }

    public void outAADiferenteAExp(AADiferenteAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAADiferenteAExp(AADiferenteAExp node)
    {
        inAADiferenteAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAADiferenteAExp(node);
    }

    public void inAAMenorIgualAExp(AAMenorIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAAMenorIgualAExp(AAMenorIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMenorIgualAExp(AAMenorIgualAExp node)
    {
        inAAMenorIgualAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAMenorIgualAExp(node);
    }

    public void inAAMaiorIgualAExp(AAMaiorIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAAMaiorIgualAExp(AAMaiorIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMaiorIgualAExp(AAMaiorIgualAExp node)
    {
        inAAMaiorIgualAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAMaiorIgualAExp(node);
    }

    public void inAAMenorAExp(AAMenorAExp node)
    {
        defaultIn(node);
    }

    public void outAAMenorAExp(AAMenorAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMenorAExp(AAMenorAExp node)
    {
        inAAMenorAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAMenorAExp(node);
    }

    public void inAAMaiorAExp(AAMaiorAExp node)
    {
        defaultIn(node);
    }

    public void outAAMaiorAExp(AAMaiorAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMaiorAExp(AAMaiorAExp node)
    {
        inAAMaiorAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAMaiorAExp(node);
    }

    public void inAASomaAExp(AASomaAExp node)
    {
        defaultIn(node);
    }

    public void outAASomaAExp(AASomaAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAASomaAExp(AASomaAExp node)
    {
        inAASomaAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAASomaAExp(node);
    }

    public void inAASubtracaoAExp(AASubtracaoAExp node)
    {
        defaultIn(node);
    }

    public void outAASubtracaoAExp(AASubtracaoAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAASubtracaoAExp(AASubtracaoAExp node)
    {
        inAASubtracaoAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAASubtracaoAExp(node);
    }

    public void inAAMultAExp(AAMultAExp node)
    {
        defaultIn(node);
    }

    public void outAAMultAExp(AAMultAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMultAExp(AAMultAExp node)
    {
        inAAMultAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAAMultAExp(node);
    }

    public void inAADivAExp(AADivAExp node)
    {
        defaultIn(node);
    }

    public void outAADivAExp(AADivAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAADivAExp(AADivAExp node)
    {
        inAADivAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAADivAExp(node);
    }

    public void inAADivIntAExp(AADivIntAExp node)
    {
        defaultIn(node);
    }

    public void outAADivIntAExp(AADivIntAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAADivIntAExp(AADivIntAExp node)
    {
        inAADivIntAExp(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAADivIntAExp(node);
    }

    public void inAAMenosUnarioAExp(AAMenosUnarioAExp node)
    {
        defaultIn(node);
    }

    public void outAAMenosUnarioAExp(AAMenosUnarioAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAMenosUnarioAExp(AAMenosUnarioAExp node)
    {
        inAAMenosUnarioAExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAAMenosUnarioAExp(node);
    }

    public void inAANegacaoAExp(AANegacaoAExp node)
    {
        defaultIn(node);
    }

    public void outAANegacaoAExp(AANegacaoAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAANegacaoAExp(AANegacaoAExp node)
    {
        inAANegacaoAExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAANegacaoAExp(node);
    }

    public void inAAVarAExp(AAVarAExp node)
    {
        defaultIn(node);
    }

    public void outAAVarAExp(AAVarAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAVarAExp(AAVarAExp node)
    {
        inAAVarAExp(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        outAAVarAExp(node);
    }

    public void inAASymbolAExp(AASymbolAExp node)
    {
        defaultIn(node);
    }

    public void outAASymbolAExp(AASymbolAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAASymbolAExp(AASymbolAExp node)
    {
        inAASymbolAExp(node);
        if(node.getValorSymbol() != null)
        {
            node.getValorSymbol().apply(this);
        }
        outAASymbolAExp(node);
    }

    public void inAAAnswerAExp(AAAnswerAExp node)
    {
        defaultIn(node);
    }

    public void outAAAnswerAExp(AAAnswerAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAAnswerAExp(AAAnswerAExp node)
    {
        inAAAnswerAExp(node);
        if(node.getValorAnswer() != null)
        {
            node.getValorAnswer().apply(this);
        }
        outAAAnswerAExp(node);
    }

    public void inAANumberAExp(AANumberAExp node)
    {
        defaultIn(node);
    }

    public void outAANumberAExp(AANumberAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAANumberAExp(AANumberAExp node)
    {
        inAANumberAExp(node);
        if(node.getValorNumber() != null)
        {
            node.getValorNumber().apply(this);
        }
        outAANumberAExp(node);
    }

    public void inAAStringAExp(AAStringAExp node)
    {
        defaultIn(node);
    }

    public void outAAStringAExp(AAStringAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAStringAExp(AAStringAExp node)
    {
        inAAStringAExp(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAAStringAExp(node);
    }
}
