/* This file was generated by SableCC (http://www.sablecc.org/). */

package tipo.analysis;

import tipo.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAArInicioAInicio(AArInicioAInicio node);
    void caseAArDeclaracoesADeclaracao(AArDeclaracoesADeclaracao node);
    void caseAArInteiroATipo(AArInteiroATipo node);
    void caseAArRealATipo(AArRealATipo node);
    void caseAIdAVar(AIdAVar node);

    void caseTBranco(TBranco node);
    void caseTInteiro(TInteiro node);
    void caseTReal(TReal node);
    void caseTVirgula(TVirgula node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
