/* This file was generated by SableCC (http://www.sablecc.org/). */

package tipo.analysis;

import java.util.*;
import tipo.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPAInicio().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAArInicioAInicio(AArInicioAInicio node)
    {
        defaultIn(node);
    }

    public void outAArInicioAInicio(AArInicioAInicio node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArInicioAInicio(AArInicioAInicio node)
    {
        inAArInicioAInicio(node);
        {
            List<PADeclaracao> copy = new ArrayList<PADeclaracao>(node.getArDeclaracoes());
            for(PADeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        outAArInicioAInicio(node);
    }

    public void inAArDeclaracoesADeclaracao(AArDeclaracoesADeclaracao node)
    {
        defaultIn(node);
    }

    public void outAArDeclaracoesADeclaracao(AArDeclaracoesADeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArDeclaracoesADeclaracao(AArDeclaracoesADeclaracao node)
    {
        inAArDeclaracoesADeclaracao(node);
        if(node.getATipo() != null)
        {
            node.getATipo().apply(this);
        }
        {
            List<PAVar> copy = new ArrayList<PAVar>(node.getIdentificadores());
            for(PAVar e : copy)
            {
                e.apply(this);
            }
        }
        outAArDeclaracoesADeclaracao(node);
    }

    public void inAArInteiroATipo(AArInteiroATipo node)
    {
        defaultIn(node);
    }

    public void outAArInteiroATipo(AArInteiroATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArInteiroATipo(AArInteiroATipo node)
    {
        inAArInteiroATipo(node);
        if(node.getInteiro() != null)
        {
            node.getInteiro().apply(this);
        }
        outAArInteiroATipo(node);
    }

    public void inAArRealATipo(AArRealATipo node)
    {
        defaultIn(node);
    }

    public void outAArRealATipo(AArRealATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArRealATipo(AArRealATipo node)
    {
        inAArRealATipo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outAArRealATipo(node);
    }

    public void inAIdAVar(AIdAVar node)
    {
        defaultIn(node);
    }

    public void outAIdAVar(AIdAVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdAVar(AIdAVar node)
    {
        inAIdAVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdAVar(node);
    }
}
