/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.analysis;

import java.util.*;
import prolixa.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaracoes(ADeclaracoes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandos(AComandos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariavelDeclaracaoInicial(AVariavelDeclaracaoInicial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstanteDeclaracaoInicial(AConstanteDeclaracaoInicial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorDeclaracaoInicial(AVetorDeclaracaoInicial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariavelDeclaracaoBloco(AVariavelDeclaracaoBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstanteDeclaracaoBloco(AConstanteDeclaracaoBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorDeclaracaoBloco(AVetorDeclaracaoBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInicializacaoVarivel(AInicializacaoVarivel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInicializacaoConstante(AInicializacaoConstante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADimensoesVetor(ADimensoesVetor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVirgulasIds(AVirgulasIds node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberTipo(ANumberTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAnswerTipo(AAnswerTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASymbolTipo(ASymbolTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComando(AComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACondicionalSimplesComandoComposto(ACondicionalSimplesComandoComposto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacoWhileComandoComposto(ALacoWhileComandoComposto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacoForComandoComposto(ALacoForComandoComposto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSimplesComandoComposto(AComandoSimplesComandoComposto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoVarComandoSimples(AAtribuicaoVarComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoConstComandoSimples(AAtribuicaoConstComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaptureComandoSimples(ACaptureComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAShowComandoSimples(AShowComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbandonComandoSimples(AAbandonComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAContinueComandoSimples(AContinueComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandoSimples(ABlocoComandoSimples node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALongAs(ALongAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInicio(AInicio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFim(AFim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIncremento(AIncremento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElseOpcional(AElseOpcional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaVars(AListaVars node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVirgulasVars(AVirgulasVars node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaExps(AListaExps node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVirgulasExps(AVirgulasExps node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaracoesBloco(ADeclaracoesBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandosBloco(AComandosBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIndicesVetor(AIndicesVetor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUnalt(AUnalt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesVar(ASimplesVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIndexadaVar(AIndexadaVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASymbolValor(ASymbolValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAnswerValor(AAnswerValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberValor(ANumberValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExp(AExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuLogicoExpOu(AOuLogicoExpOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpXorExpOu(AExpXorExpOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExclusivoExpXor(AOuExclusivoExpXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpEExpXor(AExpEExpXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAELogicoExpE(AELogicoExpE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpRelacionalExpE(AExpRelacionalExpE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExpRelacional(AIgualExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADiferenteExpRelacional(ADiferenteExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpAditivaExpRelacional(AExpAditivaExpRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpAditiva(ASomaExpAditiva node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubtracaoExpAditiva(ASubtracaoExpAditiva node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpMultiplicativaExpAditiva(AExpMultiplicativaExpAditiva node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplicacaoExpMultiplicativa(AMultiplicacaoExpMultiplicativa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivisaoExpMultiplicativa(ADivisaoExpMultiplicativa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivisaoInteiraExpMultiplicativa(ADivisaoInteiraExpMultiplicativa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpUnariaExpMultiplicativa(AExpUnariaExpMultiplicativa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosUnarioExpUnaria(AMenosUnarioExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpPrimariaExpUnaria(AExpPrimariaExpUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValorExpPrimaria(AValorExpPrimaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariavelExpPrimaria(AVariavelExpPrimaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParentesesExpPrimaria(AParentesesExpPrimaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentario(TComentario node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThis(TThis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIs(TIs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProgram(TProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIt(TIt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPresents(TPresents node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLet(TLet node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUs(TUs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBegin(TBegin node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThat(TThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWould(TWould node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBe(TBe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAll(TAll node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlterable(TAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUnalterable(TUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVector(TVector node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOf(TOf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTX(TX node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSymbol(TSymbol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnswer(TAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorSymbol(TValorSymbol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorNumber(TValorNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorAnswer(TValorAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCapture(TCapture node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTShow(TShow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTJust(TJust node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCase(TCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThat2(TThat2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOtherwise(TOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDo(TDo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAs(TAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLong(TLong node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConsidering(TConsidering node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFrom(TFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTo(TTo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBy(TBy node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbandon(TAbandon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGo(TGo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNext(TNext node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIteration(TIteration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgualAtribuicao(TIgualAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSubtracao(TSubtracao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMultiplicacao(TMultiplicacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivisao(TDivisao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivisaoInteira(TDivisaoInteira node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgualComparacao(TIgualComparacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNaoIgual(TNaoIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTXor(TXor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentesesEsquerda(TParentesesEsquerda node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParentesesDireita(TParentesesDireita node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchetesEsquerda(TColchetesEsquerda node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchetesDireita(TColchetesDireita node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspacos(TEspacos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNovasLinhas(TNovasLinhas node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
