/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.analysis;

import java.util.*;
import prolixa.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        if(node.getThis() != null)
        {
            node.getThis().apply(this);
        }
        if(node.getIs() != null)
        {
            node.getIs().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        if(node.getDeclaracoes() != null)
        {
            node.getDeclaracoes().apply(this);
        }
        if(node.getComandos() != null)
        {
            node.getComandos().apply(this);
        }
        outAPrograma(node);
    }

    public void inADeclaracoes(ADeclaracoes node)
    {
        defaultIn(node);
    }

    public void outADeclaracoes(ADeclaracoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracoes(ADeclaracoes node)
    {
        inADeclaracoes(node);
        if(node.getIt() != null)
        {
            node.getIt().apply(this);
        }
        if(node.getPresents() != null)
        {
            node.getPresents().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        {
            List<PDeclaracaoInicial> copy = new ArrayList<PDeclaracaoInicial>(node.getDeclaracaoInicial());
            for(PDeclaracaoInicial e : copy)
            {
                e.apply(this);
            }
        }
        outADeclaracoes(node);
    }

    public void inAComandos(AComandos node)
    {
        defaultIn(node);
    }

    public void outAComandos(AComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandos(AComandos node)
    {
        inAComandos(node);
        if(node.getLet() != null)
        {
            node.getLet().apply(this);
        }
        if(node.getUs() != null)
        {
            node.getUs().apply(this);
        }
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getThat() != null)
        {
            node.getThat().apply(this);
        }
        if(node.getWould() != null)
        {
            node.getWould().apply(this);
        }
        if(node.getBe() != null)
        {
            node.getBe().apply(this);
        }
        if(node.getAll() != null)
        {
            node.getAll().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAComandos(node);
    }

    public void inAVariavelDeclaracaoInicial(AVariavelDeclaracaoInicial node)
    {
        defaultIn(node);
    }

    public void outAVariavelDeclaracaoInicial(AVariavelDeclaracaoInicial node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelDeclaracaoInicial(AVariavelDeclaracaoInicial node)
    {
        inAVariavelDeclaracaoInicial(node);
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAVariavelDeclaracaoInicial(node);
    }

    public void inAConstanteDeclaracaoInicial(AConstanteDeclaracaoInicial node)
    {
        defaultIn(node);
    }

    public void outAConstanteDeclaracaoInicial(AConstanteDeclaracaoInicial node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstanteDeclaracaoInicial(AConstanteDeclaracaoInicial node)
    {
        inAConstanteDeclaracaoInicial(node);
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInicializacaoConstante() != null)
        {
            node.getInicializacaoConstante().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAConstanteDeclaracaoInicial(node);
    }

    public void inAVetorDeclaracaoInicial(AVetorDeclaracaoInicial node)
    {
        defaultIn(node);
    }

    public void outAVetorDeclaracaoInicial(AVetorDeclaracaoInicial node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVetorDeclaracaoInicial(AVetorDeclaracaoInicial node)
    {
        inAVetorDeclaracaoInicial(node);
        if(node.getVector() != null)
        {
            node.getVector().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getDimensoesVetor() != null)
        {
            node.getDimensoesVetor().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAVetorDeclaracaoInicial(node);
    }

    public void inAVariavelDeclaracaoBloco(AVariavelDeclaracaoBloco node)
    {
        defaultIn(node);
    }

    public void outAVariavelDeclaracaoBloco(AVariavelDeclaracaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelDeclaracaoBloco(AVariavelDeclaracaoBloco node)
    {
        inAVariavelDeclaracaoBloco(node);
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInicializacaoVarivel() != null)
        {
            node.getInicializacaoVarivel().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAVariavelDeclaracaoBloco(node);
    }

    public void inAConstanteDeclaracaoBloco(AConstanteDeclaracaoBloco node)
    {
        defaultIn(node);
    }

    public void outAConstanteDeclaracaoBloco(AConstanteDeclaracaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstanteDeclaracaoBloco(AConstanteDeclaracaoBloco node)
    {
        inAConstanteDeclaracaoBloco(node);
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInicializacaoConstante() != null)
        {
            node.getInicializacaoConstante().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAConstanteDeclaracaoBloco(node);
    }

    public void inAVetorDeclaracaoBloco(AVetorDeclaracaoBloco node)
    {
        defaultIn(node);
    }

    public void outAVetorDeclaracaoBloco(AVetorDeclaracaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVetorDeclaracaoBloco(AVetorDeclaracaoBloco node)
    {
        inAVetorDeclaracaoBloco(node);
        if(node.getVector() != null)
        {
            node.getVector().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getDimensoesVetor() != null)
        {
            node.getDimensoesVetor().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAVetorDeclaracaoBloco(node);
    }

    public void inAInicializacaoVarivel(AInicializacaoVarivel node)
    {
        defaultIn(node);
    }

    public void outAInicializacaoVarivel(AInicializacaoVarivel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicializacaoVarivel(AInicializacaoVarivel node)
    {
        inAInicializacaoVarivel(node);
        if(node.getIgualAtribuicao() != null)
        {
            node.getIgualAtribuicao().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAInicializacaoVarivel(node);
    }

    public void inAInicializacaoConstante(AInicializacaoConstante node)
    {
        defaultIn(node);
    }

    public void outAInicializacaoConstante(AInicializacaoConstante node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicializacaoConstante(AInicializacaoConstante node)
    {
        inAInicializacaoConstante(node);
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAInicializacaoConstante(node);
    }

    public void inADimensoesVetor(ADimensoesVetor node)
    {
        defaultIn(node);
    }

    public void outADimensoesVetor(ADimensoesVetor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADimensoesVetor(ADimensoesVetor node)
    {
        inADimensoesVetor(node);
        if(node.getX() != null)
        {
            node.getX().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outADimensoesVetor(node);
    }

    public void inAVirgulasIds(AVirgulasIds node)
    {
        defaultIn(node);
    }

    public void outAVirgulasIds(AVirgulasIds node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVirgulasIds(AVirgulasIds node)
    {
        inAVirgulasIds(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAVirgulasIds(node);
    }

    public void inANumberTipo(ANumberTipo node)
    {
        defaultIn(node);
    }

    public void outANumberTipo(ANumberTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipo(ANumberTipo node)
    {
        inANumberTipo(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberTipo(node);
    }

    public void inAAnswerTipo(AAnswerTipo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipo(AAnswerTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipo(AAnswerTipo node)
    {
        inAAnswerTipo(node);
        if(node.getAnswer() != null)
        {
            node.getAnswer().apply(this);
        }
        outAAnswerTipo(node);
    }

    public void inASymbolTipo(ASymbolTipo node)
    {
        defaultIn(node);
    }

    public void outASymbolTipo(ASymbolTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASymbolTipo(ASymbolTipo node)
    {
        inASymbolTipo(node);
        if(node.getSymbol() != null)
        {
            node.getSymbol().apply(this);
        }
        outASymbolTipo(node);
    }

    public void inAComando(AComando node)
    {
        defaultIn(node);
    }

    public void outAComando(AComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComando(AComando node)
    {
        inAComando(node);
        if(node.getComandoComposto() != null)
        {
            node.getComandoComposto().apply(this);
        }
        outAComando(node);
    }

    public void inACondicionalSimplesComandoComposto(ACondicionalSimplesComandoComposto node)
    {
        defaultIn(node);
    }

    public void outACondicionalSimplesComandoComposto(ACondicionalSimplesComandoComposto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalSimplesComandoComposto(ACondicionalSimplesComandoComposto node)
    {
        inACondicionalSimplesComandoComposto(node);
        if(node.getJust() != null)
        {
            node.getJust().apply(this);
        }
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getThat2() != null)
        {
            node.getThat2().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getComandoComposto() != null)
        {
            node.getComandoComposto().apply(this);
        }
        outACondicionalSimplesComandoComposto(node);
    }

    public void inALacoWhileComandoComposto(ALacoWhileComandoComposto node)
    {
        defaultIn(node);
    }

    public void outALacoWhileComandoComposto(ALacoWhileComandoComposto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoWhileComandoComposto(ALacoWhileComandoComposto node)
    {
        inALacoWhileComandoComposto(node);
        if(node.getAs() != null)
        {
            node.getAs().apply(this);
        }
        if(node.getLongAs() != null)
        {
            node.getLongAs().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getComandoComposto() != null)
        {
            node.getComandoComposto().apply(this);
        }
        outALacoWhileComandoComposto(node);
    }

    public void inALacoForComandoComposto(ALacoForComandoComposto node)
    {
        defaultIn(node);
    }

    public void outALacoForComandoComposto(ALacoForComandoComposto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoForComandoComposto(ALacoForComandoComposto node)
    {
        inALacoForComandoComposto(node);
        if(node.getConsidering() != null)
        {
            node.getConsidering().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getFrom() != null)
        {
            node.getFrom().apply(this);
        }
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getTo() != null)
        {
            node.getTo().apply(this);
        }
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        if(node.getBy() != null)
        {
            node.getBy().apply(this);
        }
        if(node.getIncremento() != null)
        {
            node.getIncremento().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getComandoComposto() != null)
        {
            node.getComandoComposto().apply(this);
        }
        outALacoForComandoComposto(node);
    }

    public void inAComandoSimplesComandoComposto(AComandoSimplesComandoComposto node)
    {
        defaultIn(node);
    }

    public void outAComandoSimplesComandoComposto(AComandoSimplesComandoComposto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoSimplesComandoComposto(AComandoSimplesComandoComposto node)
    {
        inAComandoSimplesComandoComposto(node);
        if(node.getComandoSimples() != null)
        {
            node.getComandoSimples().apply(this);
        }
        outAComandoSimplesComandoComposto(node);
    }

    public void inAAtribuicaoVarComandoSimples(AAtribuicaoVarComandoSimples node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoVarComandoSimples(AAtribuicaoVarComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoVarComandoSimples(AAtribuicaoVarComandoSimples node)
    {
        inAAtribuicaoVarComandoSimples(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getIgualAtribuicao() != null)
        {
            node.getIgualAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribuicaoVarComandoSimples(node);
    }

    public void inAAtribuicaoConstComandoSimples(AAtribuicaoConstComandoSimples node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoConstComandoSimples(AAtribuicaoConstComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoConstComandoSimples(AAtribuicaoConstComandoSimples node)
    {
        inAAtribuicaoConstComandoSimples(node);
        if(node.getUnalt() != null)
        {
            node.getUnalt().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribuicaoConstComandoSimples(node);
    }

    public void inACaptureComandoSimples(ACaptureComandoSimples node)
    {
        defaultIn(node);
    }

    public void outACaptureComandoSimples(ACaptureComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACaptureComandoSimples(ACaptureComandoSimples node)
    {
        inACaptureComandoSimples(node);
        if(node.getCapture() != null)
        {
            node.getCapture().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getListaVars() != null)
        {
            node.getListaVars().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outACaptureComandoSimples(node);
    }

    public void inAShowComandoSimples(AShowComandoSimples node)
    {
        defaultIn(node);
    }

    public void outAShowComandoSimples(AShowComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAShowComandoSimples(AShowComandoSimples node)
    {
        inAShowComandoSimples(node);
        if(node.getShow() != null)
        {
            node.getShow().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getListaExps() != null)
        {
            node.getListaExps().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAShowComandoSimples(node);
    }

    public void inAAbandonComandoSimples(AAbandonComandoSimples node)
    {
        defaultIn(node);
    }

    public void outAAbandonComandoSimples(AAbandonComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAbandonComandoSimples(AAbandonComandoSimples node)
    {
        inAAbandonComandoSimples(node);
        if(node.getAbandon() != null)
        {
            node.getAbandon().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAbandonComandoSimples(node);
    }

    public void inAContinueComandoSimples(AContinueComandoSimples node)
    {
        defaultIn(node);
    }

    public void outAContinueComandoSimples(AContinueComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContinueComandoSimples(AContinueComandoSimples node)
    {
        inAContinueComandoSimples(node);
        if(node.getGo() != null)
        {
            node.getGo().apply(this);
        }
        if(node.getTo() != null)
        {
            node.getTo().apply(this);
        }
        if(node.getNext() != null)
        {
            node.getNext().apply(this);
        }
        if(node.getIteration() != null)
        {
            node.getIteration().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAContinueComandoSimples(node);
    }

    public void inABlocoComandoSimples(ABlocoComandoSimples node)
    {
        defaultIn(node);
    }

    public void outABlocoComandoSimples(ABlocoComandoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComandoSimples(ABlocoComandoSimples node)
    {
        inABlocoComandoSimples(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outABlocoComandoSimples(node);
    }

    public void inALongAs(ALongAs node)
    {
        defaultIn(node);
    }

    public void outALongAs(ALongAs node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALongAs(ALongAs node)
    {
        inALongAs(node);
        if(node.getLong() != null)
        {
            node.getLong().apply(this);
        }
        if(node.getAs() != null)
        {
            node.getAs().apply(this);
        }
        outALongAs(node);
    }

    public void inAInicio(AInicio node)
    {
        defaultIn(node);
    }

    public void outAInicio(AInicio node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicio(AInicio node)
    {
        inAInicio(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAInicio(node);
    }

    public void inAFim(AFim node)
    {
        defaultIn(node);
    }

    public void outAFim(AFim node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFim(AFim node)
    {
        inAFim(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAFim(node);
    }

    public void inAIncremento(AIncremento node)
    {
        defaultIn(node);
    }

    public void outAIncremento(AIncremento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIncremento(AIncremento node)
    {
        inAIncremento(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAIncremento(node);
    }

    public void inAElseOpcional(AElseOpcional node)
    {
        defaultIn(node);
    }

    public void outAElseOpcional(AElseOpcional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseOpcional(AElseOpcional node)
    {
        inAElseOpcional(node);
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getComandoComposto() != null)
        {
            node.getComandoComposto().apply(this);
        }
        outAElseOpcional(node);
    }

    public void inAListaVars(AListaVars node)
    {
        defaultIn(node);
    }

    public void outAListaVars(AListaVars node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaVars(AListaVars node)
    {
        inAListaVars(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        {
            List<PVirgulasVars> copy = new ArrayList<PVirgulasVars>(node.getVirgulasVars());
            for(PVirgulasVars e : copy)
            {
                e.apply(this);
            }
        }
        outAListaVars(node);
    }

    public void inAVirgulasVars(AVirgulasVars node)
    {
        defaultIn(node);
    }

    public void outAVirgulasVars(AVirgulasVars node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVirgulasVars(AVirgulasVars node)
    {
        inAVirgulasVars(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVirgulasVars(node);
    }

    public void inAListaExps(AListaExps node)
    {
        defaultIn(node);
    }

    public void outAListaExps(AListaExps node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaExps(AListaExps node)
    {
        inAListaExps(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PVirgulasExps> copy = new ArrayList<PVirgulasExps>(node.getVirgulasExps());
            for(PVirgulasExps e : copy)
            {
                e.apply(this);
            }
        }
        outAListaExps(node);
    }

    public void inAVirgulasExps(AVirgulasExps node)
    {
        defaultIn(node);
    }

    public void outAVirgulasExps(AVirgulasExps node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVirgulasExps(AVirgulasExps node)
    {
        inAVirgulasExps(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAVirgulasExps(node);
    }

    public void inABloco(ABloco node)
    {
        defaultIn(node);
    }

    public void outABloco(ABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        inABloco(node);
        if(node.getColchetesEsquerda() != null)
        {
            node.getColchetesEsquerda().apply(this);
        }
        {
            List<PDeclaracoesBloco> copy = new ArrayList<PDeclaracoesBloco>(node.getDeclaracoesBloco());
            for(PDeclaracoesBloco e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PComandosBloco> copy = new ArrayList<PComandosBloco>(node.getComandosBloco());
            for(PComandosBloco e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColchetesDireita() != null)
        {
            node.getColchetesDireita().apply(this);
        }
        if(node.getElseOpcional() != null)
        {
            node.getElseOpcional().apply(this);
        }
        outABloco(node);
    }

    public void inADeclaracoesBloco(ADeclaracoesBloco node)
    {
        defaultIn(node);
    }

    public void outADeclaracoesBloco(ADeclaracoesBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracoesBloco(ADeclaracoesBloco node)
    {
        inADeclaracoesBloco(node);
        if(node.getDeclaracaoBloco() != null)
        {
            node.getDeclaracaoBloco().apply(this);
        }
        outADeclaracoesBloco(node);
    }

    public void inAComandosBloco(AComandosBloco node)
    {
        defaultIn(node);
    }

    public void outAComandosBloco(AComandosBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandosBloco(AComandosBloco node)
    {
        inAComandosBloco(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAComandosBloco(node);
    }

    public void inAIndicesVetor(AIndicesVetor node)
    {
        defaultIn(node);
    }

    public void outAIndicesVetor(AIndicesVetor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIndicesVetor(AIndicesVetor node)
    {
        inAIndicesVetor(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAIndicesVetor(node);
    }

    public void inAUnalt(AUnalt node)
    {
        defaultIn(node);
    }

    public void outAUnalt(AUnalt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnalt(AUnalt node)
    {
        inAUnalt(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAUnalt(node);
    }

    public void inASimplesVar(ASimplesVar node)
    {
        defaultIn(node);
    }

    public void outASimplesVar(ASimplesVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesVar(ASimplesVar node)
    {
        inASimplesVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outASimplesVar(node);
    }

    public void inAIndexadaVar(AIndexadaVar node)
    {
        defaultIn(node);
    }

    public void outAIndexadaVar(AIndexadaVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIndexadaVar(AIndexadaVar node)
    {
        inAIndexadaVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PIndicesVetor> copy = new ArrayList<PIndicesVetor>(node.getIndicesVetor());
            for(PIndicesVetor e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        outAIndexadaVar(node);
    }

    public void inASymbolValor(ASymbolValor node)
    {
        defaultIn(node);
    }

    public void outASymbolValor(ASymbolValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASymbolValor(ASymbolValor node)
    {
        inASymbolValor(node);
        if(node.getValorSymbol() != null)
        {
            node.getValorSymbol().apply(this);
        }
        outASymbolValor(node);
    }

    public void inAAnswerValor(AAnswerValor node)
    {
        defaultIn(node);
    }

    public void outAAnswerValor(AAnswerValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerValor(AAnswerValor node)
    {
        inAAnswerValor(node);
        if(node.getValorAnswer() != null)
        {
            node.getValorAnswer().apply(this);
        }
        outAAnswerValor(node);
    }

    public void inANumberValor(ANumberValor node)
    {
        defaultIn(node);
    }

    public void outANumberValor(ANumberValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberValor(ANumberValor node)
    {
        inANumberValor(node);
        if(node.getValorNumber() != null)
        {
            node.getValorNumber().apply(this);
        }
        outANumberValor(node);
    }

    public void inAStringValor(AStringValor node)
    {
        defaultIn(node);
    }

    public void outAStringValor(AStringValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        inAStringValor(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValor(node);
    }

    public void inAExp(AExp node)
    {
        defaultIn(node);
    }

    public void outAExp(AExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp(AExp node)
    {
        inAExp(node);
        if(node.getExpOu() != null)
        {
            node.getExpOu().apply(this);
        }
        outAExp(node);
    }

    public void inAOuLogicoExpOu(AOuLogicoExpOu node)
    {
        defaultIn(node);
    }

    public void outAOuLogicoExpOu(AOuLogicoExpOu node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuLogicoExpOu(AOuLogicoExpOu node)
    {
        inAOuLogicoExpOu(node);
        if(node.getExpOu() != null)
        {
            node.getExpOu().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpXor() != null)
        {
            node.getExpXor().apply(this);
        }
        outAOuLogicoExpOu(node);
    }

    public void inAExpXorExpOu(AExpXorExpOu node)
    {
        defaultIn(node);
    }

    public void outAExpXorExpOu(AExpXorExpOu node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpXorExpOu(AExpXorExpOu node)
    {
        inAExpXorExpOu(node);
        if(node.getExpXor() != null)
        {
            node.getExpXor().apply(this);
        }
        outAExpXorExpOu(node);
    }

    public void inAOuExclusivoExpXor(AOuExclusivoExpXor node)
    {
        defaultIn(node);
    }

    public void outAOuExclusivoExpXor(AOuExclusivoExpXor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExclusivoExpXor(AOuExclusivoExpXor node)
    {
        inAOuExclusivoExpXor(node);
        if(node.getExpXor() != null)
        {
            node.getExpXor().apply(this);
        }
        if(node.getXor() != null)
        {
            node.getXor().apply(this);
        }
        if(node.getExpE() != null)
        {
            node.getExpE().apply(this);
        }
        outAOuExclusivoExpXor(node);
    }

    public void inAExpEExpXor(AExpEExpXor node)
    {
        defaultIn(node);
    }

    public void outAExpEExpXor(AExpEExpXor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpEExpXor(AExpEExpXor node)
    {
        inAExpEExpXor(node);
        if(node.getExpE() != null)
        {
            node.getExpE().apply(this);
        }
        outAExpEExpXor(node);
    }

    public void inAELogicoExpE(AELogicoExpE node)
    {
        defaultIn(node);
    }

    public void outAELogicoExpE(AELogicoExpE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAELogicoExpE(AELogicoExpE node)
    {
        inAELogicoExpE(node);
        if(node.getExpE() != null)
        {
            node.getExpE().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAELogicoExpE(node);
    }

    public void inAExpRelacionalExpE(AExpRelacionalExpE node)
    {
        defaultIn(node);
    }

    public void outAExpRelacionalExpE(AExpRelacionalExpE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpRelacionalExpE(AExpRelacionalExpE node)
    {
        inAExpRelacionalExpE(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAExpRelacionalExpE(node);
    }

    public void inAIgualExpRelacional(AIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualExpRelacional(AIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpRelacional(AIgualExpRelacional node)
    {
        inAIgualExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getIgualComparacao() != null)
        {
            node.getIgualComparacao().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAIgualExpRelacional(node);
    }

    public void inADiferenteExpRelacional(ADiferenteExpRelacional node)
    {
        defaultIn(node);
    }

    public void outADiferenteExpRelacional(ADiferenteExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADiferenteExpRelacional(ADiferenteExpRelacional node)
    {
        inADiferenteExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getNaoIgual() != null)
        {
            node.getNaoIgual().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outADiferenteExpRelacional(node);
    }

    public void inAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        inAMenorIgualExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getMenorIgual() != null)
        {
            node.getMenorIgual().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAMenorIgualExpRelacional(node);
    }

    public void inAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        inAMaiorIgualExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getMaiorIgual() != null)
        {
            node.getMaiorIgual().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAMaiorIgualExpRelacional(node);
    }

    public void inAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        inAMenorExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAMenorExpRelacional(node);
    }

    public void inAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        inAMaiorExpRelacional(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAMaiorExpRelacional(node);
    }

    public void inAExpAditivaExpRelacional(AExpAditivaExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAExpAditivaExpRelacional(AExpAditivaExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpAditivaExpRelacional(AExpAditivaExpRelacional node)
    {
        inAExpAditivaExpRelacional(node);
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        outAExpAditivaExpRelacional(node);
    }

    public void inASomaExpAditiva(ASomaExpAditiva node)
    {
        defaultIn(node);
    }

    public void outASomaExpAditiva(ASomaExpAditiva node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpAditiva(ASomaExpAditiva node)
    {
        inASomaExpAditiva(node);
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        if(node.getSoma() != null)
        {
            node.getSoma().apply(this);
        }
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        outASomaExpAditiva(node);
    }

    public void inASubtracaoExpAditiva(ASubtracaoExpAditiva node)
    {
        defaultIn(node);
    }

    public void outASubtracaoExpAditiva(ASubtracaoExpAditiva node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtracaoExpAditiva(ASubtracaoExpAditiva node)
    {
        inASubtracaoExpAditiva(node);
        if(node.getExpAditiva() != null)
        {
            node.getExpAditiva().apply(this);
        }
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        outASubtracaoExpAditiva(node);
    }

    public void inAExpMultiplicativaExpAditiva(AExpMultiplicativaExpAditiva node)
    {
        defaultIn(node);
    }

    public void outAExpMultiplicativaExpAditiva(AExpMultiplicativaExpAditiva node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpMultiplicativaExpAditiva(AExpMultiplicativaExpAditiva node)
    {
        inAExpMultiplicativaExpAditiva(node);
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        outAExpMultiplicativaExpAditiva(node);
    }

    public void inAMultiplicacaoExpMultiplicativa(AMultiplicacaoExpMultiplicativa node)
    {
        defaultIn(node);
    }

    public void outAMultiplicacaoExpMultiplicativa(AMultiplicacaoExpMultiplicativa node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicacaoExpMultiplicativa(AMultiplicacaoExpMultiplicativa node)
    {
        inAMultiplicacaoExpMultiplicativa(node);
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        if(node.getMultiplicacao() != null)
        {
            node.getMultiplicacao().apply(this);
        }
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outAMultiplicacaoExpMultiplicativa(node);
    }

    public void inADivisaoExpMultiplicativa(ADivisaoExpMultiplicativa node)
    {
        defaultIn(node);
    }

    public void outADivisaoExpMultiplicativa(ADivisaoExpMultiplicativa node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoExpMultiplicativa(ADivisaoExpMultiplicativa node)
    {
        inADivisaoExpMultiplicativa(node);
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        if(node.getDivisao() != null)
        {
            node.getDivisao().apply(this);
        }
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outADivisaoExpMultiplicativa(node);
    }

    public void inADivisaoInteiraExpMultiplicativa(ADivisaoInteiraExpMultiplicativa node)
    {
        defaultIn(node);
    }

    public void outADivisaoInteiraExpMultiplicativa(ADivisaoInteiraExpMultiplicativa node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoInteiraExpMultiplicativa(ADivisaoInteiraExpMultiplicativa node)
    {
        inADivisaoInteiraExpMultiplicativa(node);
        if(node.getExpMultiplicativa() != null)
        {
            node.getExpMultiplicativa().apply(this);
        }
        if(node.getDivisaoInteira() != null)
        {
            node.getDivisaoInteira().apply(this);
        }
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outADivisaoInteiraExpMultiplicativa(node);
    }

    public void inAExpUnariaExpMultiplicativa(AExpUnariaExpMultiplicativa node)
    {
        defaultIn(node);
    }

    public void outAExpUnariaExpMultiplicativa(AExpUnariaExpMultiplicativa node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpUnariaExpMultiplicativa(AExpUnariaExpMultiplicativa node)
    {
        inAExpUnariaExpMultiplicativa(node);
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outAExpUnariaExpMultiplicativa(node);
    }

    public void inAMenosUnarioExpUnaria(AMenosUnarioExpUnaria node)
    {
        defaultIn(node);
    }

    public void outAMenosUnarioExpUnaria(AMenosUnarioExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosUnarioExpUnaria(AMenosUnarioExpUnaria node)
    {
        inAMenosUnarioExpUnaria(node);
        if(node.getSubtracao() != null)
        {
            node.getSubtracao().apply(this);
        }
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outAMenosUnarioExpUnaria(node);
    }

    public void inANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultIn(node);
    }

    public void outANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoExpUnaria(ANegacaoExpUnaria node)
    {
        inANegacaoExpUnaria(node);
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        if(node.getExpUnaria() != null)
        {
            node.getExpUnaria().apply(this);
        }
        outANegacaoExpUnaria(node);
    }

    public void inAExpPrimariaExpUnaria(AExpPrimariaExpUnaria node)
    {
        defaultIn(node);
    }

    public void outAExpPrimariaExpUnaria(AExpPrimariaExpUnaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpPrimariaExpUnaria(AExpPrimariaExpUnaria node)
    {
        inAExpPrimariaExpUnaria(node);
        if(node.getExpPrimaria() != null)
        {
            node.getExpPrimaria().apply(this);
        }
        outAExpPrimariaExpUnaria(node);
    }

    public void inAValorExpPrimaria(AValorExpPrimaria node)
    {
        defaultIn(node);
    }

    public void outAValorExpPrimaria(AValorExpPrimaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorExpPrimaria(AValorExpPrimaria node)
    {
        inAValorExpPrimaria(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAValorExpPrimaria(node);
    }

    public void inAVariavelExpPrimaria(AVariavelExpPrimaria node)
    {
        defaultIn(node);
    }

    public void outAVariavelExpPrimaria(AVariavelExpPrimaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelExpPrimaria(AVariavelExpPrimaria node)
    {
        inAVariavelExpPrimaria(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVariavelExpPrimaria(node);
    }

    public void inAParentesesExpPrimaria(AParentesesExpPrimaria node)
    {
        defaultIn(node);
    }

    public void outAParentesesExpPrimaria(AParentesesExpPrimaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParentesesExpPrimaria(AParentesesExpPrimaria node)
    {
        inAParentesesExpPrimaria(node);
        if(node.getParentesesEsquerda() != null)
        {
            node.getParentesesEsquerda().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getParentesesDireita() != null)
        {
            node.getParentesesDireita().apply(this);
        }
        outAParentesesExpPrimaria(node);
    }
}
