/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAnswerAExp extends PAExp
{
    private TValorAnswer _valorAnswer_;

    public AAAnswerAExp()
    {
        // Constructor
    }

    public AAAnswerAExp(
        @SuppressWarnings("hiding") TValorAnswer _valorAnswer_)
    {
        // Constructor
        setValorAnswer(_valorAnswer_);

    }

    @Override
    public Object clone()
    {
        return new AAAnswerAExp(
            cloneNode(this._valorAnswer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAnswerAExp(this);
    }

    public TValorAnswer getValorAnswer()
    {
        return this._valorAnswer_;
    }

    public void setValorAnswer(TValorAnswer node)
    {
        if(this._valorAnswer_ != null)
        {
            this._valorAnswer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorAnswer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorAnswer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorAnswer_ == child)
        {
            this._valorAnswer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorAnswer_ == oldChild)
        {
            setValorAnswer((TValorAnswer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
