/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAtribAComando extends PAComando
{
    private PAVar _variavel_;
    private PAExp _expressao_;

    public AAAtribAComando()
    {
        // Constructor
    }

    public AAAtribAComando(
        @SuppressWarnings("hiding") PAVar _variavel_,
        @SuppressWarnings("hiding") PAExp _expressao_)
    {
        // Constructor
        setVariavel(_variavel_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AAAtribAComando(
            cloneNode(this._variavel_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAtribAComando(this);
    }

    public PAVar getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PAVar node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public PAExp getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PAExp node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PAVar) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
