/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAAtribConstAComando extends PAComando
{
    private PAVar _constante_;
    private PAExp _expressao_;

    public AAAtribConstAComando()
    {
        // Constructor
    }

    public AAAtribConstAComando(
        @SuppressWarnings("hiding") PAVar _constante_,
        @SuppressWarnings("hiding") PAExp _expressao_)
    {
        // Constructor
        setConstante(_constante_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AAAtribConstAComando(
            cloneNode(this._constante_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAtribConstAComando(this);
    }

    public PAVar getConstante()
    {
        return this._constante_;
    }

    public void setConstante(PAVar node)
    {
        if(this._constante_ != null)
        {
            this._constante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constante_ = node;
    }

    public PAExp getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PAExp node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constante_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constante_ == child)
        {
            this._constante_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constante_ == oldChild)
        {
            setConstante((PAVar) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
