/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AACaptureAComando extends PAComando
{
    private PAListaVars _variaveis_;

    public AACaptureAComando()
    {
        // Constructor
    }

    public AACaptureAComando(
        @SuppressWarnings("hiding") PAListaVars _variaveis_)
    {
        // Constructor
        setVariaveis(_variaveis_);

    }

    @Override
    public Object clone()
    {
        return new AACaptureAComando(
            cloneNode(this._variaveis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAACaptureAComando(this);
    }

    public PAListaVars getVariaveis()
    {
        return this._variaveis_;
    }

    public void setVariaveis(PAListaVars node)
    {
        if(this._variaveis_ != null)
        {
            this._variaveis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variaveis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variaveis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variaveis_ == child)
        {
            this._variaveis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variaveis_ == oldChild)
        {
            setVariaveis((PAListaVars) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
