/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAForAComando extends PAComando
{
    private PAVar _variavel_;
    private PAExp _inicio_;
    private PAExp _fim_;
    private PAExp _incremento_;
    private PAComando _comando_;

    public AAForAComando()
    {
        // Constructor
    }

    public AAForAComando(
        @SuppressWarnings("hiding") PAVar _variavel_,
        @SuppressWarnings("hiding") PAExp _inicio_,
        @SuppressWarnings("hiding") PAExp _fim_,
        @SuppressWarnings("hiding") PAExp _incremento_,
        @SuppressWarnings("hiding") PAComando _comando_)
    {
        // Constructor
        setVariavel(_variavel_);

        setInicio(_inicio_);

        setFim(_fim_);

        setIncremento(_incremento_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AAForAComando(
            cloneNode(this._variavel_),
            cloneNode(this._inicio_),
            cloneNode(this._fim_),
            cloneNode(this._incremento_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAForAComando(this);
    }

    public PAVar getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PAVar node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public PAExp getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(PAExp node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public PAExp getFim()
    {
        return this._fim_;
    }

    public void setFim(PAExp node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public PAExp getIncremento()
    {
        return this._incremento_;
    }

    public void setIncremento(PAExp node)
    {
        if(this._incremento_ != null)
        {
            this._incremento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._incremento_ = node;
    }

    public PAComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PAComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._inicio_)
            + toString(this._fim_)
            + toString(this._incremento_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._incremento_ == child)
        {
            this._incremento_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PAVar) newChild);
            return;
        }

        if(this._inicio_ == oldChild)
        {
            setInicio((PAExp) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((PAExp) newChild);
            return;
        }

        if(this._incremento_ == oldChild)
        {
            setIncremento((PAExp) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PAComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
