/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAIndexadaAVar extends PAVar
{
    private TId _nome_;
    private PAExp _indice_;
    private final LinkedList<PAExp> _outrosIndices_ = new LinkedList<PAExp>();

    public AAIndexadaAVar()
    {
        // Constructor
    }

    public AAIndexadaAVar(
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") PAExp _indice_,
        @SuppressWarnings("hiding") List<?> _outrosIndices_)
    {
        // Constructor
        setNome(_nome_);

        setIndice(_indice_);

        setOutrosIndices(_outrosIndices_);

    }

    @Override
    public Object clone()
    {
        return new AAIndexadaAVar(
            cloneNode(this._nome_),
            cloneNode(this._indice_),
            cloneList(this._outrosIndices_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIndexadaAVar(this);
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExp getIndice()
    {
        return this._indice_;
    }

    public void setIndice(PAExp node)
    {
        if(this._indice_ != null)
        {
            this._indice_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._indice_ = node;
    }

    public LinkedList<PAExp> getOutrosIndices()
    {
        return this._outrosIndices_;
    }

    public void setOutrosIndices(List<?> list)
    {
        for(PAExp e : this._outrosIndices_)
        {
            e.parent(null);
        }
        this._outrosIndices_.clear();

        for(Object obj_e : list)
        {
            PAExp e = (PAExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._outrosIndices_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._indice_)
            + toString(this._outrosIndices_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._indice_ == child)
        {
            this._indice_ = null;
            return;
        }

        if(this._outrosIndices_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._indice_ == oldChild)
        {
            setIndice((PAExp) newChild);
            return;
        }

        for(ListIterator<PAExp> i = this._outrosIndices_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
