/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAListaExps extends PAListaExps
{
    private PAExp _primeira_;
    private final LinkedList<PAExp> _resto_ = new LinkedList<PAExp>();

    public AAListaExps()
    {
        // Constructor
    }

    public AAListaExps(
        @SuppressWarnings("hiding") PAExp _primeira_,
        @SuppressWarnings("hiding") List<?> _resto_)
    {
        // Constructor
        setPrimeira(_primeira_);

        setResto(_resto_);

    }

    @Override
    public Object clone()
    {
        return new AAListaExps(
            cloneNode(this._primeira_),
            cloneList(this._resto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAListaExps(this);
    }

    public PAExp getPrimeira()
    {
        return this._primeira_;
    }

    public void setPrimeira(PAExp node)
    {
        if(this._primeira_ != null)
        {
            this._primeira_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primeira_ = node;
    }

    public LinkedList<PAExp> getResto()
    {
        return this._resto_;
    }

    public void setResto(List<?> list)
    {
        for(PAExp e : this._resto_)
        {
            e.parent(null);
        }
        this._resto_.clear();

        for(Object obj_e : list)
        {
            PAExp e = (PAExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._resto_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primeira_)
            + toString(this._resto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primeira_ == child)
        {
            this._primeira_ = null;
            return;
        }

        if(this._resto_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primeira_ == oldChild)
        {
            setPrimeira((PAExp) newChild);
            return;
        }

        for(ListIterator<PAExp> i = this._resto_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
