/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAPrograma extends PAPrograma
{
    private TId _nome_;
    private PADeclaracoes _declaracoes_;
    private PAComandos _comandos_;

    public AAPrograma()
    {
        // Constructor
    }

    public AAPrograma(
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") PADeclaracoes _declaracoes_,
        @SuppressWarnings("hiding") PAComandos _comandos_)
    {
        // Constructor
        setNome(_nome_);

        setDeclaracoes(_declaracoes_);

        setComandos(_comandos_);

    }

    @Override
    public Object clone()
    {
        return new AAPrograma(
            cloneNode(this._nome_),
            cloneNode(this._declaracoes_),
            cloneNode(this._comandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAPrograma(this);
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PADeclaracoes getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(PADeclaracoes node)
    {
        if(this._declaracoes_ != null)
        {
            this._declaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoes_ = node;
    }

    public PAComandos getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(PAComandos node)
    {
        if(this._comandos_ != null)
        {
            this._comandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._declaracoes_)
            + toString(this._comandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._declaracoes_ == child)
        {
            this._declaracoes_ = null;
            return;
        }

        if(this._comandos_ == child)
        {
            this._comandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._declaracoes_ == oldChild)
        {
            setDeclaracoes((PADeclaracoes) newChild);
            return;
        }

        if(this._comandos_ == oldChild)
        {
            setComandos((PAComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
