/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAShowAComando extends PAComando
{
    private PAListaExps _expressoes_;

    public AAShowAComando()
    {
        // Constructor
    }

    public AAShowAComando(
        @SuppressWarnings("hiding") PAListaExps _expressoes_)
    {
        // Constructor
        setExpressoes(_expressoes_);

    }

    @Override
    public Object clone()
    {
        return new AAShowAComando(
            cloneNode(this._expressoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAShowAComando(this);
    }

    public PAListaExps getExpressoes()
    {
        return this._expressoes_;
    }

    public void setExpressoes(PAListaExps node)
    {
        if(this._expressoes_ != null)
        {
            this._expressoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressoes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressoes_ == child)
        {
            this._expressoes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressoes_ == oldChild)
        {
            setExpressoes((PAListaExps) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
