/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAVarInitADeclaracao extends PADeclaracao
{
    private PATipo _tipo_;
    private TId _nome_;
    private PAExp _init_;

    public AAVarInitADeclaracao()
    {
        // Constructor
    }

    public AAVarInitADeclaracao(
        @SuppressWarnings("hiding") PATipo _tipo_,
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") PAExp _init_)
    {
        // Constructor
        setTipo(_tipo_);

        setNome(_nome_);

        setInit(_init_);

    }

    @Override
    public Object clone()
    {
        return new AAVarInitADeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._nome_),
            cloneNode(this._init_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAVarInitADeclaracao(this);
    }

    public PATipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PATipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExp getInit()
    {
        return this._init_;
    }

    public void setInit(PAExp node)
    {
        if(this._init_ != null)
        {
            this._init_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._init_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._nome_)
            + toString(this._init_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._init_ == child)
        {
            this._init_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PATipo) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._init_ == oldChild)
        {
            setInit((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
