/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAVetorADeclaracao extends PADeclaracao
{
    private PATipo _tipo_;
    private TId _nome_;
    private PAExp _tamanho_;
    private PAExp _dimensoes_;

    public AAVetorADeclaracao()
    {
        // Constructor
    }

    public AAVetorADeclaracao(
        @SuppressWarnings("hiding") PATipo _tipo_,
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") PAExp _tamanho_,
        @SuppressWarnings("hiding") PAExp _dimensoes_)
    {
        // Constructor
        setTipo(_tipo_);

        setNome(_nome_);

        setTamanho(_tamanho_);

        setDimensoes(_dimensoes_);

    }

    @Override
    public Object clone()
    {
        return new AAVetorADeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._nome_),
            cloneNode(this._tamanho_),
            cloneNode(this._dimensoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAVetorADeclaracao(this);
    }

    public PATipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PATipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PAExp getTamanho()
    {
        return this._tamanho_;
    }

    public void setTamanho(PAExp node)
    {
        if(this._tamanho_ != null)
        {
            this._tamanho_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tamanho_ = node;
    }

    public PAExp getDimensoes()
    {
        return this._dimensoes_;
    }

    public void setDimensoes(PAExp node)
    {
        if(this._dimensoes_ != null)
        {
            this._dimensoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dimensoes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._nome_)
            + toString(this._tamanho_)
            + toString(this._dimensoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._tamanho_ == child)
        {
            this._tamanho_ = null;
            return;
        }

        if(this._dimensoes_ == child)
        {
            this._dimensoes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PATipo) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._tamanho_ == oldChild)
        {
            setTamanho((PAExp) newChild);
            return;
        }

        if(this._dimensoes_ == oldChild)
        {
            setDimensoes((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
