/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AAWhileAComando extends PAComando
{
    private PAExp _condicao_;
    private PAComando _comando_;

    public AAWhileAComando()
    {
        // Constructor
    }

    public AAWhileAComando(
        @SuppressWarnings("hiding") PAExp _condicao_,
        @SuppressWarnings("hiding") PAComando _comando_)
    {
        // Constructor
        setCondicao(_condicao_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AAWhileAComando(
            cloneNode(this._condicao_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAWhileAComando(this);
    }

    public PAExp getCondicao()
    {
        return this._condicao_;
    }

    public void setCondicao(PAExp node)
    {
        if(this._condicao_ != null)
        {
            this._condicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicao_ = node;
    }

    public PAComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PAComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicao_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicao_ == child)
        {
            this._condicao_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicao_ == oldChild)
        {
            setCondicao((PAExp) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PAComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
